# Library AI Project — Jupyter Notebook (Mac)

This version is modified to run locally in Jupyter Notebook/JupyterLab on macOS.

## Before running
1. Keep `dataset_univLib_preprocessed.csv` in the **same folder as this notebook**.
2. Run the installation cell below once.
3. Then run the notebook cells from top to bottom.

The original Google Colab upload/download code has been removed and replaced with normal local-file handling.

In [150]:
# Run this cell once in your Jupyter environment.
%pip install -q pandas numpy scipy scikit-learn matplotlib seaborn joblib torch transformers datasets evaluate rouge_score sentencepiece accelerate

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [151]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [152]:
import os
import pandas as pd

filename = "dataset_univLib_preprocessed.csv"

if not os.path.exists(filename):
    raise FileNotFoundError(
        f"{filename} was not found. Put the CSV file in the same folder as this Jupyter notebook.\n"
        f"Current Jupyter working directory: {os.getcwd()}"
    )

df = pd.read_csv(
    "dataset_univLib_preprocessed (1).csv",
    sep=",",
    quotechar='"'
)

print("Dataset loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Shape:", df.shape)

Dataset loaded successfully!
Rows: 52389
Columns: 22
Shape: (52389, 22)

In [153]:
df.head()

,Membership Number,Book ID Number,Trx at the year of,Borrow Duration (days),Book Title,Borrow Date,Return Date,Department Code,Cumulative GPA,Total Credit Cumulative,...,Date of Birth,Academic Year,Program Code,ISBN,DDC Number,Author,Published Year,Publisher Name,Location Code,Borrowed
0,10001,200001,5.0,50.0,Research methods for business : a skill buildi...,2018-01-02 11:58:15.643,2018-02-21 13:22:11.540,D11,3.55,41.0,...,1993-12-09,2017.0,P111,"9,78112E+12",650.072,"Sekaran, Uma",2016.0,"John Wiley & Sons, Inc",3,1
1,10001,200002,5.0,54.0,Statistics for managers using Microsoft Excel,2018-01-02 11:58:24.160,2018-02-25 15:45:14.977,D11,3.55,41.0,...,1993-12-09,2017.0,P111,"9,78129E+12",519.502 855 369,"Levine, David M.",2017.0,Pearson education asia limited,3,1
2,10003,200003,6.0,10.0,Customer relationship management,2018-01-02 12:55:36.910,2018-01-12 19:36:53.510,D11,3.66,42.0,...,1994-08-17,2016.0,P112,"9,78007E+12",658.812,"Makkar, Urvashi",2012.0,Mcgraw-hill education,3,1
3,10004,200004,1.0,11.0,A History of Japan,2018-01-02 13:10:56.520,2018-01-13 11:25:13.210,D12,3.51,146.0,...,1997-09-12,2017.0,P113,"9,78023E+12",306.095 2,"Henshall, Kenneth G.",2012.0,Palgrave Macmillan,24,1
4,10005,200005,4.0,11.0,Psikologi dan teknologi informasi,2018-01-02 13:49:27.987,2018-01-13 09:08:52.290,D12,2.86,146.0,...,1994-03-23,2014.0,P114,"9,78603E+12",158,Psikologi dan teknologi informasi,2016.0,Himpunan Psikologi Indonesia,1,1

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52389 entries, 0 to 52388
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Membership Number        52389 non-null  int64
 1   Book ID Number           52389 non-null  int64
 2   Trx at the year of       52387 non-null  float64
 3   Borrow Duration (days)   52173 non-null  float64
 4   Book Title               52389 non-null  object
 5   Borrow Date              52389 non-null  object
 6   Return Date              52173 non-null  object
 7   Department Code          52129 non-null  object
 8   Cumulative GPA           52129 non-null  float64
 9   Total Credit Cumulative  52129 non-null  float64
 10  Gender                   52129 non-null  object
 11  Place of Birth           52126 non-null  object
 12  Date of Birth            52129 non-null  object
 13  Academic Year            52129 non-null  float64
 14  Program Code             52129 non-null  object
 15  ISBN                     51040 non-null  object
 16  DDC Number               52387 non-null  object
 17  Author                   52339 non-null  object
 18  Published Year           52379 non-null  float64
 19  Publisher Name           52389 non-null  object
 20  Location Code            52389 non-null  int64
 21  Borrowed                 52389 non-null  int64
dtypes: float64(6), int64(4), object(12)
memory usage: 8.8+ MB

In [155]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Membership Number             0
Book ID Number                0
Trx at the year of            2
Borrow Duration (days)      216
Book Title                    0
Borrow Date                   0
Return Date                 216
Department Code             260
Cumulative GPA              260
Total Credit Cumulative     260
Gender                      260
Place of Birth              263
Date of Birth               260
Academic Year               260
Program Code                260
ISBN                       1349
DDC Number                    2
Author                       50
Published Year               10
Publisher Name                0
Location Code                 0
Borrowed                      0
dtype: int64

In [156]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [157]:
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
Membership Number            int64
Book ID Number               int64
Trx at the year of         float64
Borrow Duration (days)     float64
Book Title                  object
Borrow Date                 object
Return Date                 object
Department Code             object
Cumulative GPA             float64
Total Credit Cumulative    float64
Gender                      object
Place of Birth              object
Date of Birth               object
Academic Year              float64
Program Code                object
ISBN                        object
DDC Number                  object
Author                      object
Published Year             float64
Publisher Name              object
Location Code                int64
Borrowed                     int64
dtype: object

In [158]:
print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
for i, col in enumerate(df.columns, 1):
    print(i, "->", col)

Dataset shape:
(52389, 22)

Column names:
1 -> Membership Number
2 -> Book ID Number
3 -> Trx at the year of
4 -> Borrow Duration (days)
5 -> Book Title
6 -> Borrow Date
7 -> Return Date
8 -> Department Code
9 -> Cumulative GPA
10 -> Total Credit Cumulative
11 -> Gender
12 -> Place of Birth
13 -> Date of Birth
14 -> Academic Year
15 -> Program Code
16 -> ISBN
17 -> DDC Number
18 -> Author
19 -> Published Year
20 -> Publisher Name
21 -> Location Code
22 -> Borrowed

In [159]:
date_columns = [
    "Borrow Date",
    "Return Date",
    "Date of Birth"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print("Date conversion completed.\n")
print(df[date_columns].dtypes)

Date conversion completed.

Borrow Date      datetime64[ns]
Return Date      datetime64[ns]
Date of Birth    datetime64[ns]
dtype: object

In [160]:
print("Date ranges:")

print("\nBorrow Date:")
print("Minimum:", df["Borrow Date"].min())
print("Maximum:", df["Borrow Date"].max())

print("\nReturn Date:")
print("Minimum:", df["Return Date"].min())
print("Maximum:", df["Return Date"].max())

print("\nDate of Birth:")
print("Minimum:", df["Date of Birth"].min())
print("Maximum:", df["Date of Birth"].max())

Date ranges:

Borrow Date:
Minimum: 2018-01-02 11:58:15.643000
Maximum: 2025-04-09 13:09:17.570000

Return Date:
Minimum: 2018-01-03 17:31:34.487000
Maximum: 2025-04-09 12:27:46.950000

Date of Birth:
Minimum: 1958-05-21 00:00:00
Maximum: 2008-10-21 00:00:00

In [87]:
print("===== BASIC DATASET STATISTICS =====")

num_users = df["Membership Number"].nunique()
num_books = df["Book ID Number"].nunique()
num_titles = df["Book Title"].nunique()
num_transactions = len(df)

print("Number of unique users:", num_users)
print("Number of unique books:", num_books)
print("Number of unique book titles:", num_titles)
print("Number of borrowing transactions:", num_transactions)

===== BASIC DATASET STATISTICS =====
Number of unique users: 14148
Number of unique books: 8369
Number of unique book titles: 7302
Number of borrowing transactions: 52389

In [88]:
print("\n===== USER-BOOK INTERACTIONS =====")

unique_user_book_pairs = df[
    ["Membership Number", "Book ID Number"]
].drop_duplicates()

print(
    "Unique user-book interactions:",
    len(unique_user_book_pairs)
)

print(
    "Repeated borrowing records:",
    len(df) - len(unique_user_book_pairs)
)

===== USER-BOOK INTERACTIONS =====
Unique user-book interactions: 39067
Repeated borrowing records: 13322

In [89]:
user_book_counts = (
    df.groupby(
        ["Membership Number", "Book ID Number"]
    )
    .size()
    .reset_index(name="borrow_count")
)

print("===== BORROW FREQUENCY DISTRIBUTION =====")

print(
    user_book_counts["borrow_count"]
    .value_counts()
    .sort_index()
)

===== BORROW FREQUENCY DISTRIBUTION =====
borrow_count
1     32064
2      4400
3      1283
4       521
5       294
6       166
7       108
8        81
9        50
10       28
11       19
12       14
13        7
14       10
15        9
16        4
17        3
18        1
21        1
22        2
25        1
26        1
Name: count, dtype: int64

In [90]:
print("\n===== FREQUENCY SUMMARY =====")

print("Minimum:", user_book_counts["borrow_count"].min())
print("Maximum:", user_book_counts["borrow_count"].max())
print("Average:", round(user_book_counts["borrow_count"].mean(), 2))
print("Median:", user_book_counts["borrow_count"].median())

===== FREQUENCY SUMMARY =====
Minimum: 1
Maximum: 26
Average: 1.34
Median: 1.0

In [91]:
# Number of unique users and books
num_users = df["Membership Number"].nunique()
num_books = df["Book ID Number"].nunique()

# Total possible user-book combinations
total_possible_interactions = num_users * num_books

# Actual unique user-book combinations
actual_interactions = len(unique_user_book_pairs)

# Calculate sparsity and density
sparsity = (
    1 - actual_interactions / total_possible_interactions
) * 100

density = (
    actual_interactions / total_possible_interactions
) * 100

print("===== USER-BOOK MATRIX SPARSITY =====")

print("Number of users:", num_users)
print("Number of books:", num_books)
print("Possible user-book combinations:", total_possible_interactions)
print("Actual unique interactions:", actual_interactions)

print("\nSparsity:", round(sparsity, 4), "%")
print("Density:", round(density, 4), "%")

===== USER-BOOK MATRIX SPARSITY =====
Number of users: 14148
Number of books: 8369
Possible user-book combinations: 118404612
Actual unique interactions: 39067

Sparsity: 99.967 %
Density: 0.033 %

In [92]:
from scipy.sparse import csr_matrix

# Create integer IDs for users and books
user_encoder = {
    user: idx
    for idx, user in enumerate(
        df["Membership Number"].unique()
    )
}

book_encoder = {
    book: idx
    for idx, book in enumerate(
        df["Book ID Number"].unique()
    )
}

# Convert original IDs to matrix indices
user_indices = df["Membership Number"].map(user_encoder)
book_indices = df["Book ID Number"].map(book_encoder)

# Create sparse user-item matrix
interaction_matrix = csr_matrix(
    (
        [1] * len(df),
        (user_indices, book_indices)
    ),
    shape=(
        len(user_encoder),
        len(book_encoder)
    )
)

print("===== USER-ITEM MATRIX =====")
print("Matrix shape:", interaction_matrix.shape)
print("Number of non-zero entries:", interaction_matrix.nnz)
print("Matrix type:", type(interaction_matrix))

===== USER-ITEM MATRIX =====
Matrix shape: (14148, 8369)
Number of non-zero entries: 39067
Matrix type: <class 'scipy.sparse._csr.csr_matrix'>

In [93]:
interactions = (
    df[
        [
            "Membership Number",
            "Book ID Number",
            "Borrow Date"
        ]
    ]
    .drop_duplicates(
        subset=["Membership Number", "Book ID Number"]
    )
    .sort_values("Borrow Date")
    .reset_index(drop=True)
)

print("===== INTERACTION DATA =====")
print("Rows:", len(interactions))
print("Columns:", interactions.columns.tolist())

print("\nFirst 5 interactions:")
display(interactions.head())

print("\nLast 5 interactions:")
display(interactions.tail())

===== INTERACTION DATA =====
Rows: 39067
Columns: ['Membership Number', 'Book ID Number', 'Borrow Date']

First 5 interactions:

   Membership Number  Book ID Number             Borrow Date
0              10001          200001 2018-01-02 11:58:15.643
1              10001          200002 2018-01-02 11:58:24.160
2              10003          200003 2018-01-02 12:55:36.910
3              10004          200004 2018-01-02 13:10:56.520
4              10005          200005 2018-01-02 13:49:27.987

Last 5 interactions:

       Membership Number  Book ID Number             Borrow Date
39062              24147          208368 2025-04-08 15:34:42.257
39063              24147          208369 2025-04-08 15:35:14.530
39064              24148          208370 2025-04-09 12:04:49.260
39065              24148          202263 2025-04-09 12:05:23.403
39066              24149          200002 2025-04-09 13:09:17.570

In [94]:
print("===== INTERACTION TIMELINE =====")

print("Earliest interaction:")
print(interactions["Borrow Date"].min())

print("\nLatest interaction:")
print(interactions["Borrow Date"].max())

print("\nInteractions by year:")
print(
    interactions["Borrow Date"]
    .dt.year
    .value_counts()
    .sort_index()
)

===== INTERACTION TIMELINE =====
Earliest interaction:
2018-01-02 11:58:15.643000

Latest interaction:
2025-04-09 13:09:17.570000

Interactions by year:
Borrow Date
2018    13451
2019    11302
2020     2859
2021      495
2022     2278
2023     4662
2024     3277
2025      743
Name: count, dtype: int64

In [95]:
# Training data: interactions before 2025
train_interactions = interactions[
    interactions["Borrow Date"].dt.year < 2025
].copy()

# Test data: interactions from 2025
test_interactions = interactions[
    interactions["Borrow Date"].dt.year == 2025
].copy()

print("===== TEMPORAL TRAIN/TEST SPLIT =====")

print("Training interactions:", len(train_interactions))
print("Testing interactions:", len(test_interactions))

print("\nTraining period:")
print(train_interactions["Borrow Date"].min())
print("to")
print(train_interactions["Borrow Date"].max())

print("\nTesting period:")
print(test_interactions["Borrow Date"].min())
print("to")
print(test_interactions["Borrow Date"].max())

===== TEMPORAL TRAIN/TEST SPLIT =====
Training interactions: 38324
Testing interactions: 743

Training period:
2018-01-02 11:58:15.643000
to
2024-12-26 09:43:32.860000

Testing period:
2025-01-03 10:07:13.913000
to
2025-04-09 13:09:17.570000

In [96]:
train_users = set(
    train_interactions["Membership Number"]
)

test_users = set(
    test_interactions["Membership Number"]
)

known_test_users = train_users.intersection(test_users)
cold_start_users = test_users.difference(train_users)

print("===== COLD-START ANALYSIS =====")

print("Users in training:", len(train_users))
print("Users in test:", len(test_users))

print(
    "Known test users:",
    len(known_test_users)
)

print(
    "Cold-start test users:",
    len(cold_start_users)
)

print(
    "Test interactions from known users:",
    test_interactions[
        test_interactions["Membership Number"].isin(
            known_test_users
        )
    ].shape[0]
)

print(
    "Test interactions from cold-start users:",
    test_interactions[
        test_interactions["Membership Number"].isin(
            cold_start_users
        )
    ].shape[0]
)

===== COLD-START ANALYSIS =====
Users in training: 13902
Users in test: 408
Known test users: 162
Cold-start test users: 246
Test interactions from known users: 306
Test interactions from cold-start users: 437

In [97]:
from scipy.sparse import csr_matrix

# Get unique users and books from the training data
train_users = train_interactions["Membership Number"].unique()
train_books = train_interactions["Book ID Number"].unique()

# Create mappings
train_user_encoder = {
    user: idx
    for idx, user in enumerate(train_users)
}

train_book_encoder = {
    book: idx
    for idx, book in enumerate(train_books)
}

# Convert IDs to matrix indices
train_user_indices = (
    train_interactions["Membership Number"]
    .map(train_user_encoder)
)

train_book_indices = (
    train_interactions["Book ID Number"]
    .map(train_book_encoder)
)

# Create sparse training matrix
train_matrix = csr_matrix(
    (
        [1] * len(train_interactions),
        (train_user_indices, train_book_indices)
    ),
    shape=(
        len(train_user_encoder),
        len(train_book_encoder)
    )
)

print("===== TRAINING USER-ITEM MATRIX =====")

print("Matrix shape:", train_matrix.shape)
print("Non-zero interactions:", train_matrix.nnz)
print("Number of training users:", len(train_user_encoder))
print("Number of training books:", len(train_book_encoder))

===== TRAINING USER-ITEM MATRIX =====
Matrix shape: (13902, 8246)
Non-zero interactions: 38324
Number of training users: 13902
Number of training books: 8246

In [98]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate similarity between books
book_similarity = cosine_similarity(
    train_matrix.T,
    dense_output=False
)

print("===== BOOK SIMILARITY MATRIX =====")

print("Shape:", book_similarity.shape)
print("Number of non-zero similarities:", book_similarity.nnz)

===== BOOK SIMILARITY MATRIX =====
Shape: (8246, 8246)
Number of non-zero similarities: 191490

In [99]:
import numpy as np

def recommend_books(user_id, top_n=10):
    """
    Recommend books for a user using item-based collaborative filtering.
    """

    # Check whether the user exists in training data
    if user_id not in train_user_encoder:
        return None

    # Get the user's encoded index
    user_idx = train_user_encoder[user_id]

    # Get books already borrowed by the user
    user_row = train_matrix[user_idx]

    borrowed_book_indices = user_row.indices

    if len(borrowed_book_indices) == 0:
        return None

    # Accumulate recommendation scores
    scores = {}

    for book_idx in borrowed_book_indices:

        # Get similar books
        similar_books = book_similarity.getrow(book_idx)

        for recommended_idx, similarity_score in zip(
            similar_books.indices,
            similar_books.data
        ):

            # Don't recommend books already borrowed
            if recommended_idx in borrowed_book_indices:
                continue

            # Add similarity score
            scores[recommended_idx] = (
                scores.get(recommended_idx, 0)
                + similarity_score
            )

    # Sort books by recommendation score
    ranked_books = sorted(
        scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    # Convert encoded book IDs back to original IDs
    reverse_book_encoder = {
        idx: book
        for book, idx in train_book_encoder.items()
    }

    recommendations = []

    for book_idx, score in ranked_books[:top_n]:

        recommendations.append({
            "Book ID Number": reverse_book_encoder[book_idx],
            "Score": round(float(score), 4)
        })

    return recommendations

In [100]:
test_user_id = train_interactions[
    "Membership Number"
].iloc[0]

print("Test user:", test_user_id)

recommendations = recommend_books(
    test_user_id,
    top_n=10
)

print("\n===== RECOMMENDATIONS =====")

for i, rec in enumerate(recommendations, 1):
    print(
        i,
        "-> Book ID:",
        rec["Book ID Number"],
        "| Score:",
        rec["Score"]
    )

Test user: 10001

===== RECOMMENDATIONS =====
1 -> Book ID: 200361 | Score: 0.3215
2 -> Book ID: 200057 | Score: 0.3169
3 -> Book ID: 200233 | Score: 0.3064
4 -> Book ID: 200469 | Score: 0.3001
5 -> Book ID: 200127 | Score: 0.2744
6 -> Book ID: 201707 | Score: 0.2721
7 -> Book ID: 200219 | Score: 0.2488
8 -> Book ID: 200750 | Score: 0.2477
9 -> Book ID: 200773 | Score: 0.2462
10 -> Book ID: 200510 | Score: 0.2273

In [101]:
# Create a book metadata table
book_metadata = (
    df[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "ISBN",
            "Published Year",
            "Publisher Name"
        ]
    ]
    .drop_duplicates(subset=["Book ID Number"])
    .copy()
)

# Make sure Book ID has the same type
book_metadata["Book ID Number"] = book_metadata["Book ID Number"].astype(str)

# Convert recommendations into a DataFrame
rec_df = pd.DataFrame(recommendations)

# Match the Book IDs
rec_df["Book ID Number"] = rec_df["Book ID Number"].astype(str)

# Add metadata
rec_df = rec_df.merge(
    book_metadata,
    on="Book ID Number",
    how="left"
)

# Arrange columns
rec_df = rec_df[
    [
        "Book ID Number",
        "Book Title",
        "Author",
        "DDC Number",
        "ISBN",
        "Published Year",
        "Publisher Name",
        "Score"
    ]
]

# Display
display(rec_df)

,Book ID Number,Book Title,Author,DDC Number,ISBN,Published Year,Publisher Name,Score
0,200361,Operations and supply chain management,"Jacobs, F. Robert",658.05.00,"9,78008E+12",2011.0,Mcgraw-hill education,0.3215
1,200057,Digital business and e-commerce management : s...,"Chaffey, Dave",658.872,"9,78027E+12",2015.0,Pearson Education Limited,0.3169
2,200233,Marketing management,"Kotler, Philip",658.08.00,"9,78129E+12",2016.0,Pearson Education Limited,0.3064
3,200469,Accounting : tools for business decision making,"Kimmel, Paul D.",657,"9,78112E+12",2013.0,"John Wiley & Sons, Inc",0.3001
4,200127,Organizational behaviour,Organizational behaviour,658,"9,78112E+12",2015.0,"John Wiley & Sons, Inc",0.2744
5,201707,Value proposition design : how to create produ...,Value proposition design : how to create produ...,338.07.00,"9,78112E+12",2014.0,Wiley,0.2721
6,200219,Human resource management,Raymond A. Noe,658.03.00,"9,78126E+12",2017.0,Mcgraw-hill education,0.2488
7,200750,Financial management: principles and applications,"Titman, Sheridan J",658.15.00,"9,78129E+12",2014.0,Pearson Education,0.2477
8,200773,Financial accounting : tools for business deci...,"Kimmel, Paul D.",657,"9,78047E+12",2010.0,"John Wiley & Sons, Inc",0.2462
9,200510,Statistics for managers using microsoft excel,"Levine, David M",519.502 855 369,"9,78027E+12",2014.0,Pearson Education,0.2273

In [102]:
# ==========================================
# STEP 25: Evaluate Item-Based CF
# ==========================================

import numpy as np
import pandas as pd

def evaluate_recommender(test_interactions, k=10):
    precisions = []
    recalls = []

    # Only users that existed during training
    known_users = set(train_interactions["Membership Number"].unique())

    # Only evaluate known users
    test_known = test_interactions[
        test_interactions["Membership Number"].isin(known_users)
    ].copy()

    # Only books known to the training model
    known_books = set(train_interactions["Book ID Number"].unique())

    test_known = test_known[
        test_known["Book ID Number"].isin(known_books)
    ]

    for user_id, group in test_known.groupby("Membership Number"):

        # Actual books borrowed by this user in the test period
        actual_books = set(group["Book ID Number"])

        # Get recommendations
        recs = recommend_books(user_id, top_n=k)

        recommended_books = set(
            rec["Book ID Number"] for rec in recs
        )

        if len(recommended_books) == 0:
            continue

        # Number of correctly recommended books
        hits = len(actual_books & recommended_books)

        precision = hits / k
        recall = hits / len(actual_books)

        precisions.append(precision)
        recalls.append(recall)

    return {
        "Users Evaluated": len(precisions),
        "Precision@{}".format(k): np.mean(precisions),
        "Recall@{}".format(k): np.mean(recalls)
    }


# Evaluate at K = 5
results_5 = evaluate_recommender(
    test_interactions,
    k=5
)

# Evaluate at K = 10
results_10 = evaluate_recommender(
    test_interactions,
    k=10
)

print("===== EVALUATION RESULTS =====")
print()

print("Precision@5 :", round(results_5["Precision@5"], 4))
print("Recall@5    :", round(results_5["Recall@5"], 4))

print()

print("Precision@10:", round(results_10["Precision@10"], 4))
print("Recall@10   :", round(results_10["Recall@10"], 4))

print()
print("Users evaluated:", results_10["Users Evaluated"])

===== EVALUATION RESULTS =====

Precision@5 : 0.0143
Recall@5    : 0.0516

Precision@10: 0.0095
Recall@10   : 0.0638

Users evaluated: 126

In [103]:
# ==========================================
# STEP 26: Popularity-Based Baseline
# ==========================================

from collections import Counter
import numpy as np
import pandas as pd

# Count how many unique users borrowed each book
book_popularity = (
    train_interactions
    .groupby("Book ID Number")["Membership Number"]
    .nunique()
    .sort_values(ascending=False)
)

print("Most popular books in training data:")
print(book_popularity.head(10))


def popularity_recommend_books(user_id, top_n=10):

    # Books already borrowed by this user
    borrowed_books = set(
        train_interactions[
            train_interactions["Membership Number"] == user_id
        ]["Book ID Number"]
    )

    recommendations = []

    for book_id, popularity in book_popularity.items():

        if book_id in borrowed_books:
            continue

        recommendations.append({
            "Book ID Number": book_id,
            "Score": float(popularity)
        })

        if len(recommendations) >= top_n:
            break

    return recommendations


# Test with user 10001
pop_recommendations = popularity_recommend_books(
    10001,
    top_n=10
)

print("\n===== POPULARITY RECOMMENDATIONS =====")

for i, rec in enumerate(pop_recommendations, 1):
    print(
        i,
        "-> Book ID:",
        rec["Book ID Number"],
        "| Popularity:",
        rec["Score"]
    )

Most popular books in training data:
Book ID Number
200001    284
200020    209
200691    195
200078    191
200240    169
200233    165
200435    158
202502    138
200065    137
200075    135
Name: Membership Number, dtype: int64

===== POPULARITY RECOMMENDATIONS =====
1 -> Book ID: 200020 | Popularity: 209.0
2 -> Book ID: 200691 | Popularity: 195.0
3 -> Book ID: 200078 | Popularity: 191.0
4 -> Book ID: 200240 | Popularity: 169.0
5 -> Book ID: 200233 | Popularity: 165.0
6 -> Book ID: 200435 | Popularity: 158.0
7 -> Book ID: 202502 | Popularity: 138.0
8 -> Book ID: 200065 | Popularity: 137.0
9 -> Book ID: 200075 | Popularity: 135.0
10 -> Book ID: 200241 | Popularity: 129.0

In [104]:
# ==========================================
# Evaluate Popularity Baseline
# ==========================================

def evaluate_popularity(test_interactions, k=10):

    precisions = []
    recalls = []

    known_users = set(
        train_interactions["Membership Number"].unique()
    )

    known_books = set(
        train_interactions["Book ID Number"].unique()
    )

    test_known = test_interactions[
        test_interactions["Membership Number"].isin(known_users)
    ].copy()

    test_known = test_known[
        test_known["Book ID Number"].isin(known_books)
    ]

    for user_id, group in test_known.groupby("Membership Number"):

        actual_books = set(group["Book ID Number"])

        recs = popularity_recommend_books(
            user_id,
            top_n=k
        )

        recommended_books = set(
            rec["Book ID Number"]
            for rec in recs
        )

        if not recommended_books:
            continue

        hits = len(
            actual_books & recommended_books
        )

        precision = hits / k
        recall = hits / len(actual_books)

        precisions.append(precision)
        recalls.append(recall)

    return {
        "Users Evaluated": len(precisions),
        f"Precision@{k}": np.mean(precisions),
        f"Recall@{k}": np.mean(recalls)
    }


pop_5 = evaluate_popularity(
    test_interactions,
    k=5
)

pop_10 = evaluate_popularity(
    test_interactions,
    k=10
)

print("\n===== POPULARITY BASELINE =====")

print(
    "Precision@5 :",
    round(pop_5["Precision@5"], 4)
)

print(
    "Recall@5    :",
    round(pop_5["Recall@5"], 4)
)

print(
    "Precision@10:",
    round(pop_10["Precision@10"], 4)
)

print(
    "Recall@10   :",
    round(pop_10["Recall@10"], 4)
)

print(
    "Users evaluated:",
    pop_10["Users Evaluated"]
)

===== POPULARITY BASELINE =====
Precision@5 : 0.0015
Recall@5    : 0.0038
Precision@10: 0.0008
Recall@10   : 0.0038
Users evaluated: 130

In [105]:
# ==========================================
# STEP 27: MATRIX FACTORIZATION WITH SVD
# ==========================================

from sklearn.decomposition import TruncatedSVD
import numpy as np
import pandas as pd

# Use the training interaction matrix created earlier
# train_matrix shape:
# users x books

print("Training matrix shape:", train_matrix.shape)
print("Non-zero interactions:", train_matrix.nnz)

# Number of latent factors
n_components = 50

svd = TruncatedSVD(
    n_components=n_components,
    random_state=42
)

# User x latent-factor matrix
user_factors = svd.fit_transform(train_matrix)

# Book x latent-factor matrix
book_factors = svd.components_.T

print("\n===== SVD MODEL =====")
print("User factors shape:", user_factors.shape)
print("Book factors shape:", book_factors.shape)

print(
    "Explained variance ratio:",
    round(svd.explained_variance_ratio_.sum(), 4)
)

Training matrix shape: (13902, 8246)
Non-zero interactions: 38324

===== SVD MODEL =====
User factors shape: (13902, 50)
Book factors shape: (8246, 50)
Explained variance ratio: 0.1583

In [106]:
# ==========================================
# STEP 28: SVD RECOMMENDATION FUNCTION
# ==========================================

# Reverse mappings
user_to_index = {
    user_id: idx
    for idx, user_id in enumerate(train_interactions["Membership Number"].unique())
}

book_to_index = {
    book_id: idx
    for idx, book_id in enumerate(train_interactions["Book ID Number"].unique())
}

index_to_book = {
    idx: book_id
    for book_id, idx in book_to_index.items()
}


def svd_recommend_books(user_id, top_n=10):

    if user_id not in user_to_index:
        return []

    user_idx = user_to_index[user_id]

    # Predicted preference scores for every book
    scores = user_factors[user_idx].dot(book_factors.T)

    # Books already borrowed during training
    borrowed_books = set(
        train_interactions[
            train_interactions["Membership Number"] == user_id
        ]["Book ID Number"]
    )

    recommendations = []

    # Sort books by predicted score
    ranked_indices = np.argsort(scores)[::-1]

    for book_idx in ranked_indices:

        book_id = index_to_book[book_idx]

        # Don't recommend books already borrowed
        if book_id in borrowed_books:
            continue

        recommendations.append({
            "Book ID Number": book_id,
            "Score": float(scores[book_idx])
        })

        if len(recommendations) >= top_n:
            break

    return recommendations

In [107]:
# ==========================================
# TEST SVD RECOMMENDATIONS
# ==========================================

svd_recommendations = svd_recommend_books(
    10001,
    top_n=10
)

print("===== SVD RECOMMENDATIONS =====")

for i, rec in enumerate(svd_recommendations, 1):
    print(
        i,
        "-> Book ID:",
        rec["Book ID Number"],
        "| Score:",
        round(rec["Score"], 4)
    )

===== SVD RECOMMENDATIONS =====
1 -> Book ID: 200057 | Score: 0.2729
2 -> Book ID: 201707 | Score: 0.1801
3 -> Book ID: 203239 | Score: 0.1108
4 -> Book ID: 200313 | Score: 0.0852
5 -> Book ID: 200127 | Score: 0.0808
6 -> Book ID: 201690 | Score: 0.0774
7 -> Book ID: 201368 | Score: 0.0756
8 -> Book ID: 200274 | Score: 0.0709
9 -> Book ID: 200397 | Score: 0.0694
10 -> Book ID: 200434 | Score: 0.0693

In [108]:
# ==========================================
# STEP 30: EVALUATE SVD
# ==========================================

def evaluate_svd(test_interactions, k=10):

    precisions = []
    recalls = []

    # Users known during training
    known_users = set(
        train_interactions["Membership Number"].unique()
    )

    # Books known during training
    known_books = set(
        train_interactions["Book ID Number"].unique()
    )

    # Keep only known users
    test_known = test_interactions[
        test_interactions["Membership Number"].isin(known_users)
    ].copy()

    # Keep only books known to SVD
    test_known = test_known[
        test_known["Book ID Number"].isin(known_books)
    ]

    for user_id, group in test_known.groupby("Membership Number"):

        # Actual books borrowed by the user in 2025
        actual_books = set(
            group["Book ID Number"]
        )

        # SVD recommendations
        recs = svd_recommend_books(
            user_id,
            top_n=k
        )

        recommended_books = set(
            rec["Book ID Number"]
            for rec in recs
        )

        if len(recommended_books) == 0:
            continue

        # Number of correct recommendations
        hits = len(
            actual_books & recommended_books
        )

        precision = hits / k
        recall = hits / len(actual_books)

        precisions.append(precision)
        recalls.append(recall)

    return {
        "Users Evaluated": len(precisions),
        f"Precision@{k}": np.mean(precisions),
        f"Recall@{k}": np.mean(recalls)
    }


# Evaluate @5
svd_5 = evaluate_svd(
    test_interactions,
    k=5
)

# Evaluate @10
svd_10 = evaluate_svd(
    test_interactions,
    k=10
)


print("===== SVD EVALUATION =====")

print(
    "Precision@5 :",
    round(svd_5["Precision@5"], 4)
)

print(
    "Recall@5    :",
    round(svd_5["Recall@5"], 4)
)

print(
    "Precision@10:",
    round(svd_10["Precision@10"], 4)
)

print(
    "Recall@10   :",
    round(svd_10["Recall@10"], 4)
)

print(
    "Users evaluated:",
    svd_10["Users Evaluated"]
)

===== SVD EVALUATION =====
Precision@5 : 0.0138
Recall@5    : 0.0423
Precision@10: 0.0115
Recall@10   : 0.0795
Users evaluated: 130

In [109]:
# ==========================================
# STEP 31.1: PREPARE BOOK CATALOG
# ==========================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# One row per book
books = (
    df[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "Publisher Name",
            "Published Year"
        ]
    ]
    .drop_duplicates(subset=["Book ID Number"])
    .copy()
)

# Fill missing values
books["Book Title"] = books["Book Title"].fillna("")
books["Author"] = books["Author"].fillna("")
books["DDC Number"] = books["DDC Number"].fillna("")
books["Publisher Name"] = books["Publisher Name"].fillna("")
books["Published Year"] = books["Published Year"].fillna("")

# Convert everything to text
books["Book ID Number"] = books["Book ID Number"].astype(str)

# Combine useful metadata
books["content"] = (
    books["Book Title"] + " "
    + books["Author"] + " "
    + books["DDC Number"] + " "
    + books["Publisher Name"]
)

print("Number of books:", len(books))
display(books.head())

Number of books: 8369

,Book ID Number,Book Title,Author,DDC Number,Publisher Name,Published Year,content
0,200001,Research methods for business : a skill buildi...,"Sekaran, Uma",650.072,"John Wiley & Sons, Inc",2016.0,Research methods for business : a skill buildi...
1,200002,Statistics for managers using Microsoft Excel,"Levine, David M.",519.502 855 369,Pearson education asia limited,2017.0,Statistics for managers using Microsoft Excel ...
2,200003,Customer relationship management,"Makkar, Urvashi",658.812,Mcgraw-hill education,2012.0,"Customer relationship management Makkar, Urvas..."
3,200004,A History of Japan,"Henshall, Kenneth G.",306.095 2,Palgrave Macmillan,2012.0,"A History of Japan Henshall, Kenneth G. 306.09..."
4,200005,Psikologi dan teknologi informasi,Psikologi dan teknologi informasi,158,Himpunan Psikologi Indonesia,2016.0,Psikologi dan teknologi informasi Psikologi da...

In [110]:
# ==========================================
# STEP 31.2: TF-IDF REPRESENTATION
# ==========================================

tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2
)

tfidf_matrix = tfidf.fit_transform(
    books["content"]
)

print("TF-IDF matrix shape:", tfidf_matrix.shape)
print("Non-zero values:", tfidf_matrix.nnz)

TF-IDF matrix shape: (8369, 16561)
Non-zero values: 135042

In [111]:
# ==========================================
# STEP 31.3: BOOK CONTENT SIMILARITY
# ==========================================

content_similarity = cosine_similarity(
    tfidf_matrix,
    dense_output=False
)

print(
    "Content similarity shape:",
    content_similarity.shape
)

print(
    "Non-zero similarities:",
    content_similarity.nnz
)

Content similarity shape: (8369, 8369)
Non-zero similarities: 16300891

In [112]:
# ==========================================
# STEP 31.4: CONTENT-BASED RECOMMENDER
# ==========================================

book_id_to_index = {
    book_id: idx
    for idx, book_id in enumerate(books["Book ID Number"])
}

index_to_book_id = {
    idx: book_id
    for book_id, idx in book_id_to_index.items()
}


def content_recommend_books(user_id, top_n=10):

    # Get books borrowed by the user during training
    user_books = train_interactions[
        train_interactions["Membership Number"] == user_id
    ]["Book ID Number"].astype(str).unique()

    # Keep only books present in content model
    user_books = [
        book_id
        for book_id in user_books
        if book_id in book_id_to_index
    ]

    if len(user_books) == 0:
        return []

    # Accumulate similarity scores
    scores = np.zeros(len(books))

    for book_id in user_books:

        book_idx = book_id_to_index[book_id]

        scores += content_similarity[
            book_idx
        ].toarray().ravel()

    # Average across books the user borrowed
    scores = scores / len(user_books)

    # Books already borrowed
    borrowed_books = set(user_books)

    ranked_indices = np.argsort(scores)[::-1]

    recommendations = []

    for book_idx in ranked_indices:

        book_id = index_to_book_id[book_idx]

        # Don't recommend already borrowed books
        if book_id in borrowed_books:
            continue

        # Ignore zero similarity
        if scores[book_idx] <= 0:
            continue

        recommendations.append({
            "Book ID Number": book_id,
            "Score": float(scores[book_idx])
        })

        if len(recommendations) >= top_n:
            break

    return recommendations

In [113]:
# ==========================================
# TEST CONTENT-BASED RECOMMENDER
# ==========================================

content_recommendations = content_recommend_books(
    10001,
    top_n=10
)

print("===== CONTENT-BASED RECOMMENDATIONS =====")

for i, rec in enumerate(content_recommendations, 1):
    print(
        i,
        "-> Book ID:",
        rec["Book ID Number"],
        "| Score:",
        round(rec["Score"], 4)
    )

===== CONTENT-BASED RECOMMENDATIONS =====
1 -> Book ID: 206211 | Score: 0.3683
2 -> Book ID: 200528 | Score: 0.3683
3 -> Book ID: 200015 | Score: 0.3087
4 -> Book ID: 200386 | Score: 0.3087
5 -> Book ID: 200510 | Score: 0.308
6 -> Book ID: 203867 | Score: 0.2759
7 -> Book ID: 206792 | Score: 0.2493
8 -> Book ID: 201859 | Score: 0.2481
9 -> Book ID: 200856 | Score: 0.2426
10 -> Book ID: 200686 | Score: 0.2206

In [114]:
content_rec_df = pd.DataFrame(
    content_recommendations
)

content_rec_df["Book ID Number"] = (
    content_rec_df["Book ID Number"].astype(str)
)

content_rec_df = content_rec_df.merge(
    books[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "Published Year",
            "Publisher Name"
        ]
    ],
    on="Book ID Number",
    how="left"
)

display(content_rec_df)

,Book ID Number,Score,Book Title,Author,DDC Number,Published Year,Publisher Name
0,206211,0.368265,Research methods for business : a skill buildi...,"Sekaran, Uma",650.072,2020.0,"John Wiley & Sons, Inc"
1,200528,0.368265,Research methods for business : a skill-buildi...,"Sekaran, Uma",650.072,2003.0,"John Wiley & Sons, Inc"
2,200015,0.308682,Research methods for business : a skill-buildi...,"Sekaran, Uma",650.072,2013.0,Wiley
3,200386,0.308682,Research methods for business : a skill buildi...,"Sekaran, Uma",650.072,2010.0,Wiley
4,200510,0.308013,Statistics for managers using microsoft excel,"Levine, David M",519.502 855 369,2014.0,Pearson Education
5,203867,0.275935,Statistics for managers using Microsoft Excel,"Levine, David M.",519.502 855 369,2005.0,Prentice Hall
6,206792,0.249331,Statistics for managers using Microsoft Excel.,David M. Levine,519.502 855 369,2021.0,Pearson Education Limited
7,201859,0.248069,Statistics for managers using Microsoft Excel,David M. Levine,519.502 855 369,2013.0,Pearson Education
8,200856,0.242647,Statistics for managers using microsoft excel,Statistics for managers using microsoft excel,519.502 855 369,2007.0,Pearson Education
9,200686,0.220575,Statistics for managers using Microsoft Excel,Statistics for managers using microsoft Excel,519.502 855 369,2002.0,Prentice Hall

In [115]:
# ==========================================
# STEP 32: EVALUATE CONTENT-BASED MODEL
# ==========================================

def evaluate_content(test_interactions, k=10):

    precisions = []
    recalls = []

    known_users = set(
        train_interactions["Membership Number"].unique()
    )

    known_books = set(
        train_interactions["Book ID Number"].unique()
    )

    # Only users known during training
    test_known = test_interactions[
        test_interactions["Membership Number"].isin(known_users)
    ].copy()

    # Only books available to the content model
    test_known = test_known[
        test_known["Book ID Number"].isin(known_books)
    ]

    for user_id, group in test_known.groupby("Membership Number"):

        actual_books = set(group["Book ID Number"])

        recs = content_recommend_books(
            user_id,
            top_n=k
        )

        recommended_books = set(
            rec["Book ID Number"]
            for rec in recs
        )

        if len(recommended_books) == 0:
            continue

        hits = len(
            actual_books & recommended_books
        )

        precision = hits / k
        recall = hits / len(actual_books)

        precisions.append(precision)
        recalls.append(recall)

    return {
        "Users Evaluated": len(precisions),
        f"Precision@{k}": np.mean(precisions),
        f"Recall@{k}": np.mean(recalls)
    }


# Evaluate @5
content_5 = evaluate_content(
    test_interactions,
    k=5
)

# Evaluate @10
content_10 = evaluate_content(
    test_interactions,
    k=10
)

print("===== CONTENT-BASED EVALUATION =====")

print(
    "Precision@5 :",
    round(content_5["Precision@5"], 4)
)

print(
    "Recall@5    :",
    round(content_5["Recall@5"], 4)
)

print(
    "Precision@10:",
    round(content_10["Precision@10"], 4)
)

print(
    "Recall@10   :",
    round(content_10["Recall@10"], 4)
)

print(
    "Users evaluated:",
    content_10["Users Evaluated"]
)

===== CONTENT-BASED EVALUATION =====
Precision@5 : 0.0
Recall@5    : 0.0
Precision@10: 0.0
Recall@10   : 0.0
Users evaluated: 130

In [116]:
# ==========================================
# STEP 33: COLD-START ANALYSIS
# ==========================================

train_users = set(
    train_interactions["Membership Number"].unique()
)

test_users = set(
    test_interactions["Membership Number"].unique()
)

cold_start_users = test_users - train_users
known_test_users = test_users & train_users

print("===== COLD-START ANALYSIS =====")

print("Total test users      :", len(test_users))
print("Known test users      :", len(known_test_users))
print("Cold-start test users :", len(cold_start_users))

# Test interactions for cold-start users
cold_start_test = test_interactions[
    test_interactions["Membership Number"].isin(
        cold_start_users
    )
]

print()
print(
    "Cold-start interactions:",
    len(cold_start_test)
)

print(
    "Unique cold-start users:",
    cold_start_test["Membership Number"].nunique()
)

print(
    "Unique books borrowed by cold-start users:",
    cold_start_test["Book ID Number"].nunique()
)

===== COLD-START ANALYSIS =====
Total test users      : 408
Known test users      : 162
Cold-start test users : 246

Cold-start interactions: 437
Unique cold-start users: 246
Unique books borrowed by cold-start users: 332

In [117]:
# ==========================================
# STEP 34: CHECK USER ACADEMIC GROUPS
# ==========================================

user_profiles = (
    df[
        [
            "Membership Number",
            "Department Code",
            "Program Code",
            "Academic Year"
        ]
    ]
    .drop_duplicates(
        subset=["Membership Number"]
    )
)

print("Unique users:", len(user_profiles))

print("\n===== DEPARTMENT DISTRIBUTION =====")
print(
    user_profiles["Department Code"]
    .value_counts(dropna=False)
    .head(20)
)

print("\n===== PROGRAM DISTRIBUTION =====")
print(
    user_profiles["Program Code"]
    .value_counts(dropna=False)
    .head(20)
)

print("\n===== ACADEMIC YEAR DISTRIBUTION =====")
print(
    user_profiles["Academic Year"]
    .value_counts(dropna=False)
    .head(20)
)

Unique users: 14148

===== DEPARTMENT DISTRIBUTION =====
Department Code
D12    10317
D15     1158
D11      945
D14      568
D16      426
D19      300
D13      207
NaN       80
D17       63
D21       38
D18       36
D20        6
D22        3
D23        1
Name: count, dtype: int64

===== PROGRAM DISTRIBUTION =====
Program Code
P167    519
P174    402
P156    296
P111    253
P126    198
P262    195
P210    195
P171    194
P112    192
P227    181
P115    180
P142    168
P141    159
P169    158
P113    151
P131    138
P178    137
P140    135
P136    135
P154    132
Name: count, dtype: int64

===== ACADEMIC YEAR DISTRIBUTION =====
Academic Year
2018.0    2293
2017.0    2008
2016.0    1598
2019.0    1546
2022.0    1202
2014.0    1198
2015.0    1178
2023.0     865
2021.0     792
2020.0     554
2024.0     441
2013.0     276
NaN         80
2012.0      75
2011.0      39
2010.0       3
Name: count, dtype: int64

In [118]:
# ==========================================
# STEP 35.1: USER PROFILES
# ==========================================

user_profiles = (
    df[
        [
            "Membership Number",
            "Department Code",
            "Program Code",
            "Academic Year"
        ]
    ]
    .drop_duplicates(
        subset=["Membership Number"]
    )
    .copy()
)

print("User profiles:", len(user_profiles))

display(user_profiles.head())

User profiles: 14148

   Membership Number Department Code Program Code  Academic Year
0              10001             D11         P111         2017.0
2              10003             D11         P112         2016.0
3              10004             D12         P113         2017.0
4              10005             D12         P114         2014.0
5              10006             D12         P115         2014.0

In [119]:
# ==========================================
# STEP 35.2: ADD USER PROFILE TO INTERACTIONS
# ==========================================

train_with_profile = train_interactions.merge(
    user_profiles,
    on="Membership Number",
    how="left"
)

print(
    "Training interactions:",
    len(train_with_profile)
)

display(train_with_profile.head())

Training interactions: 38324

,Membership Number,Book ID Number,Borrow Date,Department Code,Program Code,Academic Year
0,10001,200001,2018-01-02 11:58:15.643,D11,P111,2017.0
1,10001,200002,2018-01-02 11:58:24.160,D11,P111,2017.0
2,10003,200003,2018-01-02 12:55:36.910,D11,P112,2016.0
3,10004,200004,2018-01-02 13:10:56.520,D12,P113,2017.0
4,10005,200005,2018-01-02 13:49:27.987,D12,P114,2014.0

In [120]:
# ==========================================
# STEP 35.3: PROGRAM-LEVEL BOOK POPULARITY
# ==========================================

program_book_popularity = (
    train_with_profile
    .dropna(subset=["Program Code"])
    .groupby(
        ["Program Code", "Book ID Number"]
    )["Membership Number"]
    .nunique()
    .reset_index(name="Popularity")
    .sort_values(
        ["Program Code", "Popularity"],
        ascending=[True, False]
    )
)

print(
    "Program-book combinations:",
    len(program_book_popularity)
)

display(
    program_book_popularity.head(20)
)

Program-book combinations: 23110

    Program Code  Book ID Number  Popularity
58          P111          200691          46
49          P111          200510          41
34          P111          200361          39
0           P111          200001          35
25          P111          200235          33
31          P111          200313          32
47          P111          200469          32
24          P111          200233          30
63          P111          200750          29
8           P111          200057          25
1           P111          200002          24
158         P111          203280          23
7           P111          200054          22
16          P111          200127          22
46          P111          200434          22
37          P111          200386          18
89          P111          201368          18
131         P111          202520          15
115         P111          201816          14
20          P111          200204          13

In [121]:
# ==========================================
# STEP 35.4: DEPARTMENT-LEVEL POPULARITY
# ==========================================

department_book_popularity = (
    train_with_profile
    .dropna(subset=["Department Code"])
    .groupby(
        ["Department Code", "Book ID Number"]
    )["Membership Number"]
    .nunique()
    .reset_index(name="Popularity")
    .sort_values(
        ["Department Code", "Popularity"],
        ascending=[True, False]
    )
)

print(
    "Department-book combinations:",
    len(department_book_popularity)
)

display(
    department_book_popularity.head(20)
)

Department-book combinations: 10478

    Department Code  Book ID Number  Popularity
127             D11          200691         183
49              D11          200233         140
0               D11          200001         115
136             D11          200750         111
11              D11          200054          84
71              D11          200361          84
94              D11          200469          84
98              D11          200510          81
212             D11          201399          76
30              D11          200127          72
50              D11          200235          70
63              D11          200313          58
74              D11          200386          56
134             D11          200748          54
1               D11          200002          51
100             D11          200525          50
97              D11          200509          46
12              D11          200057          43
73              D11          200365          39
198             D11          201368          38

In [122]:
# ==========================================
# STEP 36: COLD-START RECOMMENDER
# ==========================================

global_popularity = (
    train_interactions
    .groupby("Book ID Number")["Membership Number"]
    .nunique()
    .sort_values(ascending=False)
)


def cold_start_recommend_books(
    user_id,
    top_n=10
):

    # Find user's profile
    profile = user_profiles[
        user_profiles["Membership Number"] == user_id
    ]

    if len(profile) == 0:
        return []

    profile = profile.iloc[0]

    program = profile["Program Code"]
    department = profile["Department Code"]

    recommendations = []

    # --------------------------------------
    # LEVEL 1: PROGRAM
    # --------------------------------------

    if pd.notna(program):

        program_books = program_book_popularity[
            program_book_popularity["Program Code"]
            == program
        ]

        for _, row in program_books.iterrows():

            recommendations.append({
                "Book ID Number": row["Book ID Number"],
                "Score": float(row["Popularity"]),
                "Source": "Program"
            })

            if len(recommendations) >= top_n:
                return recommendations

    # --------------------------------------
    # LEVEL 2: DEPARTMENT
    # --------------------------------------

    if pd.notna(department):

        department_books = department_book_popularity[
            department_book_popularity["Department Code"]
            == department
        ]

        existing_books = {
            r["Book ID Number"]
            for r in recommendations
        }

        for _, row in department_books.iterrows():

            if row["Book ID Number"] in existing_books:
                continue

            recommendations.append({
                "Book ID Number": row["Book ID Number"],
                "Score": float(row["Popularity"]),
                "Source": "Department"
            })

            if len(recommendations) >= top_n:
                return recommendations

    # --------------------------------------
    # LEVEL 3: GLOBAL POPULARITY
    # --------------------------------------

    existing_books = {
        r["Book ID Number"]
        for r in recommendations
    }

    for book_id, popularity in global_popularity.items():

        if book_id in existing_books:
            continue

        recommendations.append({
            "Book ID Number": book_id,
            "Score": float(popularity),
            "Source": "Global"
        })

        if len(recommendations) >= top_n:
            break

    return recommendations

In [123]:
# ==========================================
# STEP 37: TEST COLD-START RECOMMENDER
# ==========================================

cold_user = list(cold_start_users)[0]

print("Cold-start test user:", cold_user)

cold_recommendations = cold_start_recommend_books(
    cold_user,
    top_n=10
)

print("\n===== COLD-START RECOMMENDATIONS =====")

for i, rec in enumerate(
    cold_recommendations,
    1
):
    print(
        i,
        "-> Book ID:",
        rec["Book ID Number"],
        "| Score:",
        round(rec["Score"], 4),
        "| Source:",
        rec["Source"]
    )

Cold-start test user: 24064

===== COLD-START RECOMMENDATIONS =====
1 -> Book ID: 200260 | Score: 5.0 | Source: Program
2 -> Book ID: 201707 | Score: 3.0 | Source: Program
3 -> Book ID: 206264 | Score: 3.0 | Source: Program
4 -> Book ID: 200559 | Score: 2.0 | Source: Program
5 -> Book ID: 200736 | Score: 2.0 | Source: Program
6 -> Book ID: 203638 | Score: 2.0 | Source: Program
7 -> Book ID: 206595 | Score: 2.0 | Source: Program
8 -> Book ID: 206770 | Score: 2.0 | Source: Program
9 -> Book ID: 206919 | Score: 2.0 | Source: Program
10 -> Book ID: 206972 | Score: 2.0 | Source: Program

In [124]:
cold_rec_df = pd.DataFrame(
    cold_recommendations
)

cold_rec_df["Book ID Number"] = (
    cold_rec_df["Book ID Number"].astype(str)
)

cold_rec_df = cold_rec_df.merge(
    books[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "Published Year",
            "Publisher Name"
        ]
    ],
    on="Book ID Number",
    how="left"
)

cold_rec_df = cold_rec_df[
    [
        "Book ID Number",
        "Book Title",
        "Author",
        "DDC Number",
        "Published Year",
        "Publisher Name",
        "Score",
        "Source"
    ]
]

display(cold_rec_df)

,Book ID Number,Book Title,Author,DDC Number,Published Year,Publisher Name,Score,Source
0,200260,Introduction to information systems : enabling...,"Rainer, R. Kelly",004,2011.0,Wiley,5.0,Program
1,201707,Value proposition design : how to create produ...,Value proposition design : how to create produ...,338.07.00,2014.0,Wiley,3.0,Program
2,206264,Principles of marketing,"Kotler, Philip",658.08.00,2021.0,Pearson,3.0,Program
3,200559,Business model you : a one-page method for rei...,"Clark, Tim",650.01.00,2012.0,Wiley,2.0,Program
4,200736,Understanding business,"Nickels, William G.",650,2016.0,Mc Graw-hill Companies,2.0,Program
5,203638,Bite-sized magic,"Littlewood, Kathryn",813.06.00,2015.0,Mizan,2.0,Program
6,206595,"The presentation book : how to create it, shap...","Ledden, Emma",658.452,2017.0,Pearson,2.0,Program
7,206770,Atomic habits : perubahan kecil yang memberika...,"Clear, James",155.24.00,2019.0,PT. Gramedia Pustaka Utama,2.0,Program
8,206919,Laut bercerita,Leila S. Chudori,813,2021.0,Kepustakaan Populer Gramedia,2.0,Program
9,206972,Negeri para bedebah,Tere Liye,813,2012.0,PT. Gramedia Pustaka Utama,2.0,Program

In [125]:
# ============================================
# STEP 38: COLD-START EVALUATION
# ============================================

def evaluate_cold_start_model(top_n=5):

    precisions = []
    recalls = []

    evaluated_users = 0
    total_hits = 0
    total_relevant = 0

    for user_id in cold_start_users:

        # --------------------------------------------
        # 1. Actual books borrowed by this user in 2025
        # --------------------------------------------
        actual_books = set(
            test_interactions[
                test_interactions["Membership Number"] == user_id
            ]["Book ID Number"]
        )

        if len(actual_books) == 0:
            continue

        # --------------------------------------------
        # 2. Generate recommendations
        # --------------------------------------------
        recs = cold_start_recommend_books(
            user_id,
            top_n=top_n
        )

        if recs is None or len(recs) == 0:
            continue

        # --------------------------------------------
        # 3. Extract recommended Book IDs
        # --------------------------------------------

        # Your cold_start_recommend_books() returns a LIST
        # of dictionaries, so extract Book ID Number
        # from each dictionary.

        recommended_books = set()

        for rec in recs:

            if isinstance(rec, dict):
                if "Book ID Number" in rec:
                    recommended_books.add(rec["Book ID Number"])

            else:
                # If the function returns tuples/lists,
                # handle the first element as Book ID.
                try:
                    recommended_books.add(rec[0])
                except:
                    pass

        if len(recommended_books) == 0:
            continue

        # --------------------------------------------
        # 4. Calculate hits
        # --------------------------------------------

        hits = len(
            recommended_books.intersection(actual_books)
        )

        precision = hits / len(recommended_books)
        recall = hits / len(actual_books)

        precisions.append(precision)
        recalls.append(recall)

        total_hits += hits
        total_relevant += len(actual_books)

        evaluated_users += 1

    # --------------------------------------------
    # 5. Return results
    # --------------------------------------------

    return {
        "Precision": (
            sum(precisions) / len(precisions)
            if precisions else 0
        ),

        "Recall": (
            sum(recalls) / len(recalls)
            if recalls else 0
        ),

        "Users Evaluated": evaluated_users,

        "Total Hits": total_hits,

        "Total Relevant": total_relevant
    }


# ============================================
# RUN EVALUATION
# ============================================

cold_start_at5 = evaluate_cold_start_model(top_n=5)

cold_start_at10 = evaluate_cold_start_model(top_n=10)


print("===== COLD-START EVALUATION =====")

print("\nPrecision@5:",
      round(cold_start_at5["Precision"], 4))

print("Recall@5:",
      round(cold_start_at5["Recall"], 4))

print("Users Evaluated:",
      cold_start_at5["Users Evaluated"])


print("\nPrecision@10:",
      round(cold_start_at10["Precision"], 4))

print("Recall@10:",
      round(cold_start_at10["Recall"], 4))

print("Users Evaluated:",
      cold_start_at10["Users Evaluated"])

===== COLD-START EVALUATION =====

Precision@5: 0.035
Recall@5: 0.1093
Users Evaluated: 246

Precision@10: 0.0224
Recall@10: 0.1352
Users Evaluated: 246

In [126]:
# ============================================
# STEP 39: COLD-START RECOMMENDATION COVERAGE
# ============================================

total_cold_users = len(cold_start_users)

users_with_recommendations = 0

for user_id in cold_start_users:

    recs = cold_start_recommend_books(
        user_id,
        top_n=10
    )

    if recs is not None and len(recs) > 0:
        users_with_recommendations += 1


coverage = users_with_recommendations / total_cold_users


print("===== COLD-START COVERAGE =====")

print("Total cold-start users:",
      total_cold_users)

print("Users receiving recommendations:",
      users_with_recommendations)

print("Coverage:",
      round(coverage, 4))

print("Coverage %:",
      round(coverage * 100, 2))

===== COLD-START COVERAGE =====
Total cold-start users: 246
Users receiving recommendations: 246
Coverage: 1.0
Coverage %: 100.0

In [127]:
# ============================================
# STEP 40: CURRENT MODEL SUMMARY
# ============================================

model_results = pd.DataFrame([
    {
        "Model": "Popularity",
        "Precision@5": 0.0015,
        "Recall@5": 0.0038,
        "Precision@10": 0.0008,
        "Recall@10": 0.0038
    },
    {
        "Model": "Item-CF",
        "Precision@5": 0.0143,
        "Recall@5": 0.0516,
        "Precision@10": 0.0095,
        "Recall@10": 0.0638
    },
    {
        "Model": "SVD",
        "Precision@5": 0.0138,
        "Recall@5": 0.0423,
        "Precision@10": 0.0115,
        "Recall@10": 0.0795
    },
    {
        "Model": "Content-Based",
        "Precision@5": 0.0000,
        "Recall@5": 0.0000,
        "Precision@10": 0.0000,
        "Recall@10": 0.0000
    },
    {
        "Model": "Cold-Start Academic Group",
        "Precision@5": cold_start_at5["Precision"],
        "Recall@5": cold_start_at5["Recall"],
        "Precision@10": cold_start_at10["Precision"],
        "Recall@10": cold_start_at10["Recall"]
    }
])

model_results

                       Model  Precision@5  Recall@5  Precision@10  Recall@10
0                 Popularity     0.001500   0.00380      0.000800    0.00380
1                    Item-CF     0.014300   0.05160      0.009500    0.06380
2                        SVD     0.013800   0.04230      0.011500    0.07950
3              Content-Based     0.000000   0.00000      0.000000    0.00000
4  Cold-Start Academic Group     0.034959   0.10935      0.022358    0.13523

In [128]:
# ============================================
# STEP 42: HYBRID RECOMMENDER
# ============================================

def hybrid_recommend_books(user_id, top_n=10):

    # ----------------------------------------
    # Check whether user has training history
    # ----------------------------------------

    user_has_history = user_id in user_to_index

    # ----------------------------------------
    # COLD-START USER
    # ----------------------------------------

    if not user_has_history:

        return cold_start_recommend_books(
            user_id,
            top_n=top_n
        )


    # ========================================
    # KNOWN USER
    # ========================================

    # Get Item-CF recommendations
    cf_recs = recommend_books(
        user_id,
        top_n=top_n * 3
    )

    # Get SVD recommendations
    svd_recs = svd_recommend_books(
        user_id,
        top_n=top_n * 3
    )

    # ----------------------------------------
    # Store combined scores
    # ----------------------------------------

    scores = {}


    # ========================================
    # ITEM-CF SCORE
    # ========================================

    if cf_recs is not None and len(cf_recs) > 0:

        for rec in cf_recs:

            book_id = rec["Book ID Number"]
            score = rec["Score"]

            scores[book_id] = scores.get(book_id, 0) + (
                0.5 * score
            )


    # ========================================
    # SVD SCORE
    # ========================================

    if svd_recs is not None and len(svd_recs) > 0:

        for rec in svd_recs:

            book_id = rec["Book ID Number"]
            score = rec["Score"]

            scores[book_id] = scores.get(book_id, 0) + (
                0.5 * score
            )


    # ----------------------------------------
    # Sort combined recommendations
    # ----------------------------------------

    ranked_books = sorted(
        scores.items(),
        key=lambda x: x[1],
        reverse=True
    )


    # ----------------------------------------
    # Return top N
    # ----------------------------------------

    recommendations = []

    for book_id, score in ranked_books[:top_n]:

        recommendations.append({
            "Book ID Number": book_id,
            "Score": score,
            "Source": "Hybrid"
        })


    return recommendations

In [129]:
# ============================================
# TEST HYBRID - KNOWN USER
# ============================================

test_known_user = 10001

hybrid_known = hybrid_recommend_books(
    test_known_user,
    top_n=10
)

print("===== HYBRID RECOMMENDATIONS =====")

for i, rec in enumerate(hybrid_known, start=1):

    print(
        f"{i} -> "
        f"Book ID: {rec['Book ID Number']} | "
        f"Score: {rec['Score']:.4f} | "
        f"Source: {rec['Source']}"
    )

===== HYBRID RECOMMENDATIONS =====
1 -> Book ID: 200057 | Score: 0.2949 | Source: Hybrid
2 -> Book ID: 201707 | Score: 0.2261 | Source: Hybrid
3 -> Book ID: 200127 | Score: 0.1776 | Source: Hybrid
4 -> Book ID: 200361 | Score: 0.1608 | Source: Hybrid
5 -> Book ID: 200219 | Score: 0.1588 | Source: Hybrid
6 -> Book ID: 200233 | Score: 0.1532 | Source: Hybrid
7 -> Book ID: 200469 | Score: 0.1500 | Source: Hybrid
8 -> Book ID: 203239 | Score: 0.1427 | Source: Hybrid
9 -> Book ID: 200313 | Score: 0.1423 | Source: Hybrid
10 -> Book ID: 200773 | Score: 0.1415 | Source: Hybrid

In [130]:
# ============================================
# TEST HYBRID - COLD-START USER
# ============================================

test_cold_user = 24064

hybrid_cold = hybrid_recommend_books(
    test_cold_user,
    top_n=10
)

print("===== HYBRID COLD-START RECOMMENDATIONS =====")

for i, rec in enumerate(hybrid_cold, start=1):

    print(
        f"{i} -> "
        f"Book ID: {rec['Book ID Number']} | "
        f"Score: {rec['Score']:.4f} | "
        f"Source: {rec['Source']}"
    )

===== HYBRID COLD-START RECOMMENDATIONS =====
1 -> Book ID: 200260 | Score: 5.0000 | Source: Program
2 -> Book ID: 201707 | Score: 3.0000 | Source: Program
3 -> Book ID: 206264 | Score: 3.0000 | Source: Program
4 -> Book ID: 200559 | Score: 2.0000 | Source: Program
5 -> Book ID: 200736 | Score: 2.0000 | Source: Program
6 -> Book ID: 203638 | Score: 2.0000 | Source: Program
7 -> Book ID: 206595 | Score: 2.0000 | Source: Program
8 -> Book ID: 206770 | Score: 2.0000 | Source: Program
9 -> Book ID: 206919 | Score: 2.0000 | Source: Program
10 -> Book ID: 206972 | Score: 2.0000 | Source: Program

In [131]:
# ============================================
# STEP 44: DISPLAY HYBRID RECOMMENDATIONS
# FIXED VERSION
# ============================================

def display_hybrid_recommendations(user_id, top_n=10):

    recs = hybrid_recommend_books(
        user_id,
        top_n=top_n
    )

    if recs is None or len(recs) == 0:
        print("No recommendations available.")
        return

    # Convert recommendations to DataFrame
    rec_df = pd.DataFrame(recs)

    # ----------------------------------------
    # FIX: Make Book ID type consistent
    # ----------------------------------------

    rec_df["Book ID Number"] = (
        rec_df["Book ID Number"]
        .astype(str)
        .str.strip()
    )

    books_display = books[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "Published Year",
            "Publisher Name"
        ]
    ].copy()

    books_display["Book ID Number"] = (
        books_display["Book ID Number"]
        .astype(str)
        .str.strip()
    )

    # ----------------------------------------
    # Merge recommendations with book metadata
    # ----------------------------------------

    display_df = rec_df.merge(
        books_display,
        on="Book ID Number",
        how="left"
    )

    # ----------------------------------------
    # Arrange columns
    # ----------------------------------------

    return display_df[
        [
            "Book ID Number",
            "Book Title",
            "Author",
            "DDC Number",
            "Published Year",
            "Publisher Name",
            "Score",
            "Source"
        ]
    ]


# ============================================
# TEST WITH KNOWN USER
# ============================================

display_hybrid_recommendations(
    user_id=10001,
    top_n=10
)

,Book ID Number,Book Title,Author,DDC Number,Published Year,Publisher Name,Score,Source
0,200057,Digital business and e-commerce management : s...,"Chaffey, Dave",658.872,2015.0,Pearson Education Limited,0.294925,Hybrid
1,201707,Value proposition design : how to create produ...,Value proposition design : how to create produ...,338.07.00,2014.0,Wiley,0.226116,Hybrid
2,200127,Organizational behaviour,Organizational behaviour,658,2015.0,"John Wiley & Sons, Inc",0.177589,Hybrid
3,200361,Operations and supply chain management,"Jacobs, F. Robert",658.05.00,2011.0,Mcgraw-hill education,0.160750,Hybrid
4,200219,Human resource management,Raymond A. Noe,658.03.00,2017.0,Mcgraw-hill education,0.158834,Hybrid
5,200233,Marketing management,"Kotler, Philip",658.08.00,2016.0,Pearson Education Limited,0.153200,Hybrid
6,200469,Accounting : tools for business decision making,"Kimmel, Paul D.",657,2013.0,"John Wiley & Sons, Inc",0.150050,Hybrid
7,203239,The design thinking playbook : mindful digital...,"Lewrick, Michael",658.409 4,2018.0,Wiley,0.142696,Hybrid
8,200313,Crafting and executing strategy : the quest fo...,Crafting and executing strategy : the quest fo...,658.401 2,2018.0,Mcgraw-hill education,0.142317,Hybrid
9,200773,Financial accounting : tools for business deci...,"Kimmel, Paul D.",657,2010.0,"John Wiley & Sons, Inc",0.141506,Hybrid

In [132]:
# ============================================
# TEST WITH COLD-START USER
# ============================================

display_hybrid_recommendations(
    user_id=24064,
    top_n=10
)

,Book ID Number,Book Title,Author,DDC Number,Published Year,Publisher Name,Score,Source
0,200260,Introduction to information systems : enabling...,"Rainer, R. Kelly",004,2011.0,Wiley,5.0,Program
1,201707,Value proposition design : how to create produ...,Value proposition design : how to create produ...,338.07.00,2014.0,Wiley,3.0,Program
2,206264,Principles of marketing,"Kotler, Philip",658.08.00,2021.0,Pearson,3.0,Program
3,200559,Business model you : a one-page method for rei...,"Clark, Tim",650.01.00,2012.0,Wiley,2.0,Program
4,200736,Understanding business,"Nickels, William G.",650,2016.0,Mc Graw-hill Companies,2.0,Program
5,203638,Bite-sized magic,"Littlewood, Kathryn",813.06.00,2015.0,Mizan,2.0,Program
6,206595,"The presentation book : how to create it, shap...","Ledden, Emma",658.452,2017.0,Pearson,2.0,Program
7,206770,Atomic habits : perubahan kecil yang memberika...,"Clear, James",155.24.00,2019.0,PT. Gramedia Pustaka Utama,2.0,Program
8,206919,Laut bercerita,Leila S. Chudori,813,2021.0,Kepustakaan Populer Gramedia,2.0,Program
9,206972,Negeri para bedebah,Tere Liye,813,2012.0,PT. Gramedia Pustaka Utama,2.0,Program

In [133]:
# ============================================
# STEP 45: DEFINE COMMON KNOWN-USER TEST SET
# ============================================

# Users that existed in the training data
known_users = set(train_interactions["Membership Number"].unique())

# Users appearing in the 2025 test set
test_users = set(test_interactions["Membership Number"].unique())

# Users that are known to the recommender
known_test_users = known_users.intersection(test_users)

print("===== COMMON KNOWN-USER TEST SET =====")

print("Training users:", len(known_users))
print("2025 test users:", len(test_users))
print("Known test users:", len(known_test_users))

===== COMMON KNOWN-USER TEST SET =====
Training users: 13902
2025 test users: 408
Known test users: 162

In [134]:
# ============================================
# STEP 46: HYBRID EVALUATION
# ============================================

def evaluate_hybrid_model(
    evaluation_users,
    top_n=10
):

    precisions = []
    recalls = []

    total_hits = 0
    total_relevant = 0
    evaluated_users = 0

    for user_id in evaluation_users:

        # ------------------------------------
        # Actual books borrowed in 2025
        # ------------------------------------

        actual_books = set(
            test_interactions[
                test_interactions["Membership Number"] == user_id
            ]["Book ID Number"]
        )

        if len(actual_books) == 0:
            continue

        # ------------------------------------
        # Generate hybrid recommendations
        # ------------------------------------

        recs = hybrid_recommend_books(
            user_id,
            top_n=top_n
        )

        if recs is None or len(recs) == 0:
            continue

        # ------------------------------------
        # Extract recommended Book IDs
        # ------------------------------------

        recommended_books = set()

        for rec in recs:

            if isinstance(rec, dict):

                if "Book ID Number" in rec:
                    recommended_books.add(
                        rec["Book ID Number"]
                    )

            else:

                try:
                    recommended_books.add(rec[0])
                except:
                    pass

        if len(recommended_books) == 0:
            continue

        # ------------------------------------
        # Calculate hits
        # ------------------------------------

        hits = len(
            recommended_books.intersection(
                actual_books
            )
        )

        precision = (
            hits / len(recommended_books)
        )

        recall = (
            hits / len(actual_books)
        )

        precisions.append(precision)
        recalls.append(recall)

        total_hits += hits
        total_relevant += len(actual_books)

        evaluated_users += 1

    # ----------------------------------------
    # Return evaluation results
    # ----------------------------------------

    return {
        "Precision": (
            sum(precisions) / len(precisions)
            if precisions else 0
        ),

        "Recall": (
            sum(recalls) / len(recalls)
            if recalls else 0
        ),

        "Users Evaluated": evaluated_users,

        "Total Hits": total_hits,

        "Total Relevant": total_relevant
    }

In [135]:
# ============================================
# RUN HYBRID EVALUATION
# ============================================

hybrid_at5 = evaluate_hybrid_model(
    known_test_users,
    top_n=5
)

hybrid_at10 = evaluate_hybrid_model(
    known_test_users,
    top_n=10
)


print("===== HYBRID EVALUATION =====")

print("\nPrecision@5:",
      round(hybrid_at5["Precision"], 4))

print("Recall@5:",
      round(hybrid_at5["Recall"], 4))

print("Users Evaluated:",
      hybrid_at5["Users Evaluated"])


print("\nPrecision@10:",
      round(hybrid_at10["Precision"], 4))

print("Recall@10:",
      round(hybrid_at10["Recall"], 4))

print("Users Evaluated:",
      hybrid_at10["Users Evaluated"])

===== HYBRID EVALUATION =====

Precision@5: 0.0123
Recall@5: 0.0427
Users Evaluated: 162

Precision@10: 0.008
Recall@10: 0.0516
Users Evaluated: 162

In [136]:
# ============================================
# STEP 48: NORMALIZED HYBRID RECOMMENDER
# ============================================

def normalize_scores(recommendations):

    if recommendations is None or len(recommendations) == 0:
        return {}

    scores = {}

    for rec in recommendations:

        book_id = rec["Book ID Number"]
        score = float(rec["Score"])

        scores[book_id] = score

    if len(scores) == 0:
        return {}

    min_score = min(scores.values())
    max_score = max(scores.values())

    # Avoid division by zero
    if max_score == min_score:
        return {
            book_id: 1.0
            for book_id in scores
        }

    normalized = {
        book_id:
        (score - min_score) / (max_score - min_score)
        for book_id, score in scores.items()
    }

    return normalized


def normalized_hybrid_recommend_books(
    user_id,
    top_n=10,
    cf_weight=0.5,
    svd_weight=0.5
):

    # ========================================
    # COLD-START USER
    # ========================================

    if user_id not in user_to_index:

        return cold_start_recommend_books(
            user_id,
            top_n=top_n
        )

    # ========================================
    # KNOWN USER
    # ========================================

    cf_recs = recommend_books(
        user_id,
        top_n=top_n * 3
    )

    svd_recs = svd_recommend_books(
        user_id,
        top_n=top_n * 3
    )

    # ========================================
    # NORMALIZE SCORES
    # ========================================

    cf_scores = normalize_scores(cf_recs)
    svd_scores = normalize_scores(svd_recs)

    # ========================================
    # COMBINE
    # ========================================

    combined_scores = {}

    all_books = set(
        cf_scores.keys()
    ).union(
        svd_scores.keys()
    )

    for book_id in all_books:

        cf_score = cf_scores.get(
            book_id,
            0
        )

        svd_score = svd_scores.get(
            book_id,
            0
        )

        combined_score = (
            cf_weight * cf_score
            +
            svd_weight * svd_score
        )

        combined_scores[book_id] = combined_score

    # ========================================
    # RANK
    # ========================================

    ranked_books = sorted(
        combined_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    # ========================================
    # TOP-N
    # ========================================

    recommendations = []

    for book_id, score in ranked_books[:top_n]:

        recommendations.append({
            "Book ID Number": book_id,
            "Score": score,
            "Source": "Normalized Hybrid"
        })

    return recommendations

In [137]:
# ============================================
# STEP 49: TEST NORMALIZED HYBRID
# ============================================

normalized_hybrid = normalized_hybrid_recommend_books(
    user_id=10001,
    top_n=10
)

print("===== NORMALIZED HYBRID =====")

for i, rec in enumerate(
    normalized_hybrid,
    start=1
):

    print(
        f"{i} -> "
        f"Book ID: {rec['Book ID Number']} | "
        f"Score: {rec['Score']:.4f} | "
        f"Source: {rec['Source']}"
    )

===== NORMALIZED HYBRID =====
1 -> Book ID: 200057 | Score: 0.9858 | Source: Normalized Hybrid
2 -> Book ID: 201707 | Score: 0.6561 | Source: Normalized Hybrid
3 -> Book ID: 200361 | Score: 0.5000 | Source: Normalized Hybrid
4 -> Book ID: 200127 | Score: 0.4580 | Source: Normalized Hybrid
5 -> Book ID: 200233 | Score: 0.4535 | Source: Normalized Hybrid
6 -> Book ID: 200469 | Score: 0.4340 | Source: Normalized Hybrid
7 -> Book ID: 200219 | Score: 0.3545 | Source: Normalized Hybrid
8 -> Book ID: 200773 | Score: 0.2802 | Source: Normalized Hybrid
9 -> Book ID: 200750 | Score: 0.2725 | Source: Normalized Hybrid
10 -> Book ID: 200313 | Score: 0.2360 | Source: Normalized Hybrid

In [138]:
# ============================================
# STEP 50: EVALUATE NORMALIZED HYBRID
# ============================================

def evaluate_normalized_hybrid(
    evaluation_users,
    top_n=10
):

    precisions = []
    recalls = []

    evaluated_users = 0

    for user_id in evaluation_users:

        actual_books = set(
            test_interactions[
                test_interactions["Membership Number"] == user_id
            ]["Book ID Number"]
        )

        if len(actual_books) == 0:
            continue

        recs = normalized_hybrid_recommend_books(
            user_id,
            top_n=top_n
        )

        if recs is None or len(recs) == 0:
            continue

        recommended_books = set()

        for rec in recs:

            if isinstance(rec, dict):

                if "Book ID Number" in rec:
                    recommended_books.add(
                        rec["Book ID Number"]
                    )

        if len(recommended_books) == 0:
            continue

        hits = len(
            recommended_books.intersection(
                actual_books
            )
        )

        precision = (
            hits / len(recommended_books)
        )

        recall = (
            hits / len(actual_books)
        )

        precisions.append(precision)
        recalls.append(recall)

        evaluated_users += 1

    return {
        "Precision": (
            sum(precisions) / len(precisions)
            if precisions else 0
        ),

        "Recall": (
            sum(recalls) / len(recalls)
            if recalls else 0
        ),

        "Users Evaluated": evaluated_users
    }


# ============================================
# RUN NORMALIZED HYBRID EVALUATION
# ============================================

normalized_hybrid_at5 = evaluate_normalized_hybrid(
    known_test_users,
    top_n=5
)

normalized_hybrid_at10 = evaluate_normalized_hybrid(
    known_test_users,
    top_n=10
)

print("===== NORMALIZED HYBRID EVALUATION =====")

print(
    "\nPrecision@5:",
    round(
        normalized_hybrid_at5["Precision"],
        4
    )
)

print(
    "Recall@5:",
    round(
        normalized_hybrid_at5["Recall"],
        4
    )
)

print(
    "Users Evaluated:",
    normalized_hybrid_at5["Users Evaluated"]
)

print(
    "\nPrecision@10:",
    round(
        normalized_hybrid_at10["Precision"],
        4
    )
)

print(
    "Recall@10:",
    round(
        normalized_hybrid_at10["Recall"],
        4
    )
)

print(
    "Users Evaluated:",
    normalized_hybrid_at10["Users Evaluated"]
)

===== NORMALIZED HYBRID EVALUATION =====

Precision@5: 0.0148
Recall@5: 0.0445
Users Evaluated: 162

Precision@10: 0.0099
Recall@10: 0.062
Users Evaluated: 162

In [139]:
# ============================================
# FINAL RECOMMENDER COMPARISON
# ============================================

results = pd.DataFrame([
    {
        "Model": "Original Hybrid",
        "Precision@5": hybrid_at5["Precision"],
        "Recall@5": hybrid_at5["Recall"],
        "Precision@10": hybrid_at10["Precision"],
        "Recall@10": hybrid_at10["Recall"]
    },
    {
        "Model": "Normalized Hybrid",
        "Precision@5": normalized_hybrid_at5["Precision"],
        "Recall@5": normalized_hybrid_at5["Recall"],
        "Precision@10": normalized_hybrid_at10["Precision"],
        "Recall@10": normalized_hybrid_at10["Recall"]
    }
])

display(
    results.round(4)
)

               Model  Precision@5  Recall@5  Precision@10  Recall@10
0    Original Hybrid       0.0123    0.0427        0.0080     0.0516
1  Normalized Hybrid       0.0148    0.0445        0.0099     0.0620

In [140]:
# ============================================
# STEP 51: COMMON-POPULATION EVALUATION
# ============================================

def evaluate_model_common(
    recommend_function,
    evaluation_users,
    top_n=10
):

    precisions = []
    recalls = []

    evaluated_users = 0

    for user_id in evaluation_users:

        # Actual held-out books
        actual_books = set(
            test_interactions[
                test_interactions["Membership Number"] == user_id
            ]["Book ID Number"]
        )

        if len(actual_books) == 0:
            continue

        # Generate recommendations
        recs = recommend_function(
            user_id,
            top_n=top_n
        )

        if recs is None or len(recs) == 0:
            continue

        recommended_books = set()

        for rec in recs:

            if isinstance(rec, dict):
                if "Book ID Number" in rec:
                    recommended_books.add(
                        rec["Book ID Number"]
                    )

        if len(recommended_books) == 0:
            continue

        # Calculate hits
        hits = len(
            recommended_books.intersection(
                actual_books
            )
        )

        precision = (
            hits / len(recommended_books)
        )

        recall = (
            hits / len(actual_books)
        )

        precisions.append(precision)
        recalls.append(recall)

        evaluated_users += 1

    return {
        "Precision": (
            sum(precisions) / len(precisions)
            if precisions else 0
        ),
        "Recall": (
            sum(recalls) / len(recalls)
            if recalls else 0
        ),
        "Users Evaluated": evaluated_users
    }

In [141]:
# ============================================
# STEP 52: EVALUATE ALL MODELS
# ============================================

models = {
    "Popularity": popularity_recommend_books,
    "Item-CF": recommend_books,
    "SVD": svd_recommend_books,
    "Content-Based": content_recommend_books,
    "Original Hybrid": hybrid_recommend_books,
    "Normalized Hybrid": normalized_hybrid_recommend_books
}

final_results = []

for model_name, model_function in models.items():

    print(f"Evaluating {model_name}...")

    result_5 = evaluate_model_common(
        model_function,
        known_test_users,
        top_n=5
    )

    result_10 = evaluate_model_common(
        model_function,
        known_test_users,
        top_n=10
    )

    final_results.append({
        "Model": model_name,
        "Precision@5": result_5["Precision"],
        "Recall@5": result_5["Recall"],
        "Precision@10": result_10["Precision"],
        "Recall@10": result_10["Recall"],
        "Users Evaluated": result_10["Users Evaluated"]
    })

final_results_df = pd.DataFrame(final_results)

display(
    final_results_df.round(4)
)

Evaluating Popularity...
Evaluating Item-CF...
Evaluating SVD...
Evaluating Content-Based...
Evaluating Original Hybrid...
Evaluating Normalized Hybrid...

,Model,Precision@5,Recall@5,Precision@10,Recall@10,Users Evaluated
0,Popularity,0.0012,0.0021,0.0006,0.0021,162
1,Item-CF,0.0115,0.0377,0.0076,0.0469,157
2,SVD,0.0111,0.0337,0.0093,0.0635,162
3,Content-Based,0.0000,0.0000,0.0000,0.0000,162
4,Original Hybrid,0.0123,0.0427,0.0080,0.0516,162
5,Normalized Hybrid,0.0148,0.0445,0.0099,0.0620,162

In [142]:
# ============================================
# STEP 53: CREATE MODEL ARTIFACT DIRECTORY
# ============================================

import os

artifact_dir = "library_recommender_artifacts"

os.makedirs(artifact_dir, exist_ok=True)

print("Artifact directory created:")
print(artifact_dir)

Artifact directory created:
library_recommender_artifacts

In [143]:
# ============================================
# STEP 54: SAVE RECOMMENDER ARTIFACTS
# ============================================

import joblib

# --------------------------------------------
# 1. Item-CF similarity matrix
# --------------------------------------------

joblib.dump(
    book_similarity,
    f"{artifact_dir}/book_similarity.joblib"
)


# --------------------------------------------
# 2. SVD model
# --------------------------------------------

joblib.dump(
    svd,
    f"{artifact_dir}/svd_model.joblib"
)


# --------------------------------------------
# 3. SVD factors
# --------------------------------------------

joblib.dump(
    user_factors,
    f"{artifact_dir}/user_factors.joblib"
)

joblib.dump(
    book_factors,
    f"{artifact_dir}/book_factors.joblib"
)


# --------------------------------------------
# 4. User and book mappings
# --------------------------------------------

joblib.dump(
    user_to_index,
    f"{artifact_dir}/user_to_index.joblib"
)

joblib.dump(
    book_to_index,
    f"{artifact_dir}/book_to_index.joblib"
)


# --------------------------------------------
# 5. Book metadata
# --------------------------------------------

joblib.dump(
    books,
    f"{artifact_dir}/books_metadata.joblib"
)


# --------------------------------------------
# 6. User profiles
# --------------------------------------------

joblib.dump(
    user_profiles,
    f"{artifact_dir}/user_profiles.joblib"
)


# --------------------------------------------
# 7. Popularity tables
# --------------------------------------------

joblib.dump(
    program_book_popularity,
    f"{artifact_dir}/program_book_popularity.joblib"
)

joblib.dump(
    department_book_popularity,
    f"{artifact_dir}/department_book_popularity.joblib"
)

joblib.dump(
    global_popularity,
    f"{artifact_dir}/global_popularity.joblib"
)


print("All recommendation artifacts saved successfully.")

All recommendation artifacts saved successfully.

In [144]:
# ============================================
# STEP 55: VERIFY ARTIFACTS
# ============================================

for filename in sorted(os.listdir(artifact_dir)):

    filepath = os.path.join(
        artifact_dir,
        filename
    )

    size_mb = os.path.getsize(filepath) / (
        1024 * 1024
    )

    print(
        f"{filename:45s} "
        f"{size_mb:.2f} MB"
    )

book_factors.joblib                           3.15 MB
book_similarity.joblib                        2.22 MB
book_to_index.joblib                          0.17 MB
books_metadata.joblib                         1.58 MB
department_book_popularity.joblib             0.26 MB
global_popularity.joblib                      0.25 MB
program_book_popularity.joblib                0.59 MB
svd_model.joblib                              3.15 MB
user_factors.joblib                           5.30 MB
user_profiles.joblib                          0.40 MB
user_to_index.joblib                          0.29 MB

In [145]:
# ============================================
# STEP 56: ZIP RECOMMENDER ARTIFACTS
# ============================================

import shutil
import os

zip_path = shutil.make_archive(
    "library_recommender_artifacts",
    "zip",
    artifact_dir
)

print("Created:")
print(zip_path)

print(
    "Size:",
    round(os.path.getsize(zip_path) / (1024 * 1024), 2),
    "MB"
)

Created:
/Users/hemanthreddy/Downloads/library_recommender_artifacts.zip
Size: 11.67 MB

In [146]:
# ============================================
# LOCAL JUPYTER: ARTIFACT ZIP LOCATION
# ============================================

import os

zip_file = os.path.abspath("library_recommender_artifacts.zip")

print("Artifact ZIP created at:")
print(zip_file)
print("You can open this location from Finder if needed.")

Artifact ZIP created at:
/Users/hemanthreddy/Downloads/library_recommender_artifacts.zip
You can open this location from Finder if needed.

In [147]:
# ============================================
# LOCAL JUPYTER: CLEANED DATASET LOCATION
# ============================================

import os

dataset_file = os.path.abspath("dataset_univLib_preprocessed.csv")

print("Dataset file location:")
print(dataset_file)

Dataset file location:
/Users/hemanthreddy/Downloads/dataset_univLib_preprocessed.csv

In [148]:
# ============================================================
# STEP 59: INSTALL NLP LIBRARIES (JUPYTER/MAC)
# ============================================================

%pip install -q -U transformers datasets evaluate rouge_score sentencepiece accelerate

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [149]:
# Check whether a GPU backend is available

import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

# Apple Silicon Macs can use Apple's MPS backend when supported.
mps_available = hasattr(torch.backends, "mps") and torch.backends.mps.is_available()
print("Apple MPS available:", mps_available)

if mps_available:
    print("Apple GPU backend (MPS) is available.")
elif torch.cuda.is_available():
    print("CUDA GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU backend detected. The notebook can still run on CPU.")

PyTorch version: 2.14.0
CUDA available: False
Apple MPS available: True
Apple GPU backend (MPS) is available.

In [161]:
import platform
import sys

print("Operating system:", platform.system())
print("Machine:", platform.machine())
print("Python version:", sys.version)

Operating system: Darwin
Machine: arm64
Python version: 3.13.7 (v3.13.7:bcee1c32211, Aug 14 2025, 19:10:51) [Clang 16.0.0 (clang-1600.0.26.6)]

In [162]:
# ============================================================
# STEP 59.1: TEST APPLE GPU (MPS)
# ============================================================

import torch

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

print("Selected device:", device)

if device.type == "mps":
    print("✅ Apple GPU (MPS) is ready for NLP training.")
else:
    print("⚠️ MPS is not available. Using CPU.")

Selected device: mps
✅ Apple GPU (MPS) is ready for NLP training.

In [163]:
# ============================================================
# STEP 59.2: CHECK NLP LIBRARIES
# ============================================================

import torch
import transformers
import datasets
import evaluate

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("Evaluate:", evaluate.__version__)

print("\nSelected device:", device)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PyTorch: 2.14.0
Transformers: 5.17.0
Datasets: 5.0.1
Evaluate: 0.4.6

Selected device: mps

In [164]:
# ============================================================
# STEP 59.3: LOAD EXISTING SUMMARIZATION DATASET
# ============================================================

from datasets import load_dataset

print("Loading CNN/DailyMail dataset...")

dataset = load_dataset(
    "abisee/cnn_dailymail",
    "3.0.0"
)

print("\nDataset loaded successfully!")
print(dataset)

Loading CNN/DailyMail dataset...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 287113/287113 [00:01<00:00, 205111.51 examples/s]
Generating validation split: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13368/13368 [00:00<00:00, 193284.97 examples/s]
Generating test split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11490/11490 [00:00<00:00, 204451.77 examples/s]

Dataset loaded successfully!
DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})

In [169]:
# ============================================================
# STEP 59.4: INSPECT SUMMARIZATION DATASET
# ============================================================

# Show available columns
print("Columns:")
print(dataset["train"].column_names)

# Get the first training example
example = dataset["train"][0]

print("\n" + "="*80)
print("ARTICLE")
print("="*80)
print(example["article"])

print("\n" + "="*80)
print("SUMMARY")
print("="*80)
print(example["highlights"])

print("\n" + "="*80)
print("ARTICLE CHARACTER COUNT:", len(example["article"]))
print("SUMMARY CHARACTER COUNT:", len(example["highlights"]))
print("="*80)

Columns:
['article', 'highlights', 'id']

================================================================================
ARTICLE
================================================================================
LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he'll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I'll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe's earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say 'kid star goes off the rails,'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter's latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he is braced for even closer media scrutiny now that he's legally an adult: "I just think I'm going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.

================================================================================
SUMMARY
================================================================================
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

================================================================================
ARTICLE CHARACTER COUNT: 2527
SUMMARY CHARACTER COUNT: 217
================================================================================

In [170]:
# ============================================================
# STEP 60.1: ANALYZE ARTICLE AND SUMMARY LENGTHS
# ============================================================

import pandas as pd

# Convert the training dataset to a pandas DataFrame
train_df = dataset["train"].to_pandas()

# Calculate word counts
train_df["article_words"] = train_df["article"].str.split().str.len()
train_df["summary_words"] = train_df["highlights"].str.split().str.len()

print("Number of training examples:", len(train_df))

print("\nArticle word count statistics:")
print(train_df["article_words"].describe())

print("\nSummary word count statistics:")
print(train_df["summary_words"].describe())

Number of training examples: 287113

Article word count statistics:
count    287113.000000
mean        691.870326
std         336.500292
min           8.000000
25%         443.000000
50%         632.000000
75%         877.000000
max        2347.000000
Name: article_words, dtype: float64

Summary word count statistics:
count    287113.000000
mean         51.574101
std          21.256336
min           4.000000
25%          38.000000
50%          48.000000
75%          60.000000
max        1296.000000
Name: summary_words, dtype: float64

In [171]:
# ============================================================
# STEP 60.2: CREATE PRACTICAL TRAINING SUBSETS
# ============================================================

TRAIN_SIZE = 20_000
VALIDATION_SIZE = 2_000
TEST_SIZE = 2_000

train_small = dataset["train"].shuffle(seed=42).select(range(TRAIN_SIZE))
validation_small = dataset["validation"].shuffle(seed=42).select(range(VALIDATION_SIZE))
test_small = dataset["test"].shuffle(seed=42).select(range(TEST_SIZE))

print("Training examples:", len(train_small))
print("Validation examples:", len(validation_small))
print("Test examples:", len(test_small))

Training examples: 20000
Validation examples: 2000
Test examples: 2000

In [172]:
# ============================================================
# STEP 60.3: LOAD T5-SMALL TOKENIZER
# ============================================================

from transformers import AutoTokenizer

model_checkpoint = "google-t5/t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

print("Tokenizer loaded successfully.")
print("Model checkpoint:", model_checkpoint)
print("Vocabulary size:", tokenizer.vocab_size)

Tokenizer loaded successfully.
Model checkpoint: google-t5/t5-small
Vocabulary size: 32100

In [173]:
# ============================================================
# STEP 60.4: TEST T5 TOKENIZATION
# ============================================================

sample_article = train_small[0]["article"]
sample_summary = train_small[0]["highlights"]

# T5 expects a task prefix for summarization
input_text = "summarize: " + sample_article

# Tokenize the article
input_tokens = tokenizer(
    input_text,
    max_length=512,
    truncation=True
)

# Tokenize the target summary
target_tokens = tokenizer(
    text_target=sample_summary,
    max_length=128,
    truncation=True
)

print("Original article words:", len(sample_article.split()))
print("Original summary words:", len(sample_summary.split()))

print("\nTokenized input length:", len(input_tokens["input_ids"]))
print("Tokenized target length:", len(target_tokens["input_ids"]))

print("\nFirst 20 input token IDs:")
print(input_tokens["input_ids"][:20])

print("\nFirst 20 target token IDs:")
print(target_tokens["input_ids"][:20])

Original article words: 537
Original summary words: 33

Tokenized input length: 512
Tokenized target length: 48

First 20 input token IDs:
[21603, 10, 938, 3, 5, 11016, 12528, 3, 5, 3, 10744, 8775, 20619, 2326, 10, 3, 5, 10668, 10, 4928]

First 20 target token IDs:
[1079, 11, 3, 5, 31423, 6176, 130, 3883, 5815, 70, 3062, 6, 7758, 60, 35, 3, 5, 328, 130, 435]

In [174]:
# ============================================================
# STEP 60.5: TOKENIZE TRAIN / VALIDATION / TEST DATA
# ============================================================

def preprocess_function(examples):
    # Add T5 task prefix
    inputs = ["summarize: " + article for article in examples["article"]]

    # Tokenize articles
    model_inputs = tokenizer(
        inputs,
        max_length=512,
        truncation=True
    )

    # Tokenize summaries as target labels
    labels = tokenizer(
        text_target=examples["highlights"],
        max_length=128,
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs


print("Tokenizing training data...")
tokenized_train = train_small.map(
    preprocess_function,
    batched=True,
    remove_columns=train_small.column_names
)

print("Tokenizing validation data...")
tokenized_validation = validation_small.map(
    preprocess_function,
    batched=True,
    remove_columns=validation_small.column_names
)

print("Tokenizing test data...")
tokenized_test = test_small.map(
    preprocess_function,
    batched=True,
    remove_columns=test_small.column_names
)

print("\nTokenization completed successfully.")

print("\nDataset sizes:")
print("Train:", len(tokenized_train))
print("Validation:", len(tokenized_validation))
print("Test:", len(tokenized_test))

print("\nTokenized columns:")
print(tokenized_train.column_names)

print("\nFirst training example:")
print("Input token count:", len(tokenized_train[0]["input_ids"]))
print("Label token count:", len(tokenized_train[0]["labels"]))

Tokenizing training data...

Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20000/20000 [00:08<00:00, 2356.88 examples/s]

Tokenizing validation data...

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:01<00:00, 1856.69 examples/s]

Tokenizing test data...

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:00<00:00, 2018.28 examples/s]

Tokenization completed successfully.

Dataset sizes:
Train: 20000
Validation: 2000
Test: 2000

Tokenized columns:
['input_ids', 'attention_mask', 'labels']

First training example:
Input token count: 512
Label token count: 48

In [175]:
# ============================================================
# STEP 60.6: LOAD T5-SMALL MODEL
# ============================================================

from transformers import AutoModelForSeq2SeqLM

print("Loading T5-small model...")

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_checkpoint
)

print("\nModel loaded successfully.")
print("Model checkpoint:", model_checkpoint)

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)

print("Total parameters:", f"{total_params:,}")
print("Trainable parameters:", f"{trainable_params:,}")

# Move model to Apple GPU
model = model.to(device)

print("\nModel device:", next(model.parameters()).device)

Loading T5-small model...

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 131/131 [00:00<00:00, 10990.18it/s]

Model loaded successfully.
Model checkpoint: google-t5/t5-small
Total parameters: 60,506,624
Trainable parameters: 60,506,624

Model device: mps:0

In [176]:
# ============================================================
# STEP 60.7: TEST T5 FORWARD PASS ON APPLE MPS
# ============================================================

import torch

# Take one tokenized training example
sample = tokenized_train[0]

# Convert to tensors and add batch dimension
input_ids = torch.tensor(
    [sample["input_ids"]],
    dtype=torch.long,
    device=device
)

attention_mask = torch.tensor(
    [sample["attention_mask"]],
    dtype=torch.long,
    device=device
)

labels = torch.tensor(
    [sample["labels"]],
    dtype=torch.long,
    device=device
)

print("Input shape:", input_ids.shape)
print("Attention mask shape:", attention_mask.shape)
print("Labels shape:", labels.shape)
print("Device:", input_ids.device)

# Forward pass
model.eval()

with torch.no_grad():
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        labels=labels
    )

print("\nForward pass successful!")
print("Loss:", outputs.loss.item())
print("Logits shape:", outputs.logits.shape)

Input shape: torch.Size([1, 512])
Attention mask shape: torch.Size([1, 512])
Labels shape: torch.Size([1, 48])
Device: mps:0

Forward pass successful!
Loss: 1.770945429801941
Logits shape: torch.Size([1, 48, 32128])

In [177]:
# ============================================================
# STEP 60.8: CHECK MAC MEMORY
# ============================================================

import psutil

memory = psutil.virtual_memory()

print("Total system memory:", round(memory.total / (1024**3), 2), "GB")
print("Available memory:", round(memory.available / (1024**3), 2), "GB")
print("Used memory:", round(memory.used / (1024**3), 2), "GB")
print("Memory usage:", memory.percent, "%")

Total system memory: 16.0 GB
Available memory: 5.41 GB
Used memory: 7.08 GB
Memory usage: 66.2 %

In [178]:
# ============================================================
# STEP 60.9: CONFIGURE T5 TRAINING
# ============================================================

# Training configuration
TRAIN_BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 5e-5
NUM_EPOCHS = 1

# Sequence lengths
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 128

# Reproducibility
RANDOM_SEED = 42

print("T5 Training Configuration")
print("=" * 40)

print("Model:", model_checkpoint)
print("Device:", device)

print("\nBatch size:", TRAIN_BATCH_SIZE)
print("Gradient accumulation:", GRADIENT_ACCUMULATION_STEPS)
print(
    "Effective batch size:",
    TRAIN_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS
)

print("\nLearning rate:", LEARNING_RATE)
print("Epochs:", NUM_EPOCHS)

print("\nMaximum input tokens:", MAX_INPUT_LENGTH)
print("Maximum target tokens:", MAX_TARGET_LENGTH)

print("\nMixed precision: Disabled")
print("Random seed:", RANDOM_SEED)

T5 Training Configuration
========================================
Model: google-t5/t5-small
Device: mps

Batch size: 2
Gradient accumulation: 4
Effective batch size: 8

Learning rate: 5e-05
Epochs: 1

Maximum input tokens: 512
Maximum target tokens: 128

Mixed precision: Disabled
Random seed: 42

In [179]:
# ============================================================
# STEP 60.10: PREPARE DATALOADER AND OPTIMIZER
# ============================================================

import torch
from torch.utils.data import DataLoader
from transformers import DataCollatorForSeq2Seq
from torch.optim import AdamW

# ------------------------------------------------------------
# Data collator
# ------------------------------------------------------------
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,
    return_tensors="pt"
)

# ------------------------------------------------------------
# DataLoaders
# ------------------------------------------------------------
train_dataloader = DataLoader(
    tokenized_train,
    batch_size=TRAIN_BATCH_SIZE,
    shuffle=True,
    collate_fn=data_collator
)

validation_dataloader = DataLoader(
    tokenized_validation,
    batch_size=TRAIN_BATCH_SIZE,
    shuffle=False,
    collate_fn=data_collator
)

# ------------------------------------------------------------
# Optimizer
# ------------------------------------------------------------
optimizer = AdamW(
    model.parameters(),
    lr=LEARNING_RATE
)

# ------------------------------------------------------------
# Calculate number of optimization steps
# ------------------------------------------------------------
steps_per_epoch = len(train_dataloader) // GRADIENT_ACCUMULATION_STEPS

total_training_steps = steps_per_epoch * NUM_EPOCHS

print("DataLoader and optimizer prepared successfully.")
print()
print("Training batches:", len(train_dataloader))
print("Validation batches:", len(validation_dataloader))
print("Steps per epoch:", steps_per_epoch)
print("Total optimization steps:", total_training_steps)
print()
print("Optimizer:", type(optimizer).__name__)
print("Learning rate:", LEARNING_RATE)

DataLoader and optimizer prepared successfully.

Training batches: 10000
Validation batches: 1000
Steps per epoch: 2500
Total optimization steps: 2500

Optimizer: AdamW
Learning rate: 5e-05

In [180]:
# ============================================================
# STEP 60.11: TEST ONE TRAINING BATCH ON APPLE MPS
# ============================================================

import torch

# Put model into training mode
model.train()

# Get one batch
batch = next(iter(train_dataloader))

# Move batch tensors to MPS
batch = {
    key: value.to(device)
    for key, value in batch.items()
}

print("Batch shapes:")
for key, value in batch.items():
    print(f"{key}: {value.shape}")

print("\nDevice:", batch["input_ids"].device)

# Clear previous gradients
optimizer.zero_grad()

# Forward pass
outputs = model(**batch)

loss = outputs.loss

print("\nForward pass successful.")
print("Loss before backward:", loss.item())

# Backward pass
loss.backward()

print("Backward pass successful.")

# Optimizer update
optimizer.step()

print("Optimizer step successful.")
print("\n✅ Single-batch training test passed.")

Batch shapes:
input_ids: torch.Size([2, 512])
attention_mask: torch.Size([2, 512])
labels: torch.Size([2, 95])
decoder_input_ids: torch.Size([2, 95])

Device: mps:0

Forward pass successful.
Loss before backward: 3.291749954223633
Backward pass successful.
Optimizer step successful.

✅ Single-batch training test passed.

In [181]:
# ============================================================
# STEP 60.12: RESET MODEL TO ORIGINAL T5-SMALL WEIGHTS
# ============================================================

from transformers import AutoModelForSeq2SeqLM
from torch.optim import AdamW

print("Reloading original T5-small weights...")

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_checkpoint
)

# Move model to Apple GPU
model = model.to(device)

# Recreate optimizer for the fresh model
optimizer = AdamW(
    model.parameters(),
    lr=LEARNING_RATE
)

# Verify
total_params = sum(p.numel() for p in model.parameters())

print("\nModel reset successfully.")
print("Model:", model_checkpoint)
print("Parameters:", f"{total_params:,}")
print("Device:", next(model.parameters()).device)
print("Learning rate:", LEARNING_RATE)

print("\n✅ Model is ready for the real training run.")

Reloading original T5-small weights...

Loading weights: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 131/131 [00:00<00:00, 6027.16it/s]

Model reset successfully.
Model: google-t5/t5-small
Parameters: 60,506,624
Device: mps:0
Learning rate: 5e-05

✅ Model is ready for the real training run.

In [182]:
# ============================================================
# STEP 60.13: TRAIN T5-SMALL FOR 1 EPOCH
# ============================================================

import time
import torch

# ------------------------------------------------------------
# Training setup
# ------------------------------------------------------------

torch.manual_seed(RANDOM_SEED)

model.train()

total_batches = len(train_dataloader)
total_steps = total_batches // GRADIENT_ACCUMULATION_STEPS

running_loss = 0.0
epoch_loss = 0.0
optimizer.zero_grad()

start_time = time.time()

print("Starting T5-small training...")
print("=" * 60)
print("Training examples:", len(tokenized_train))
print("Epochs:", NUM_EPOCHS)
print("Batch size:", TRAIN_BATCH_SIZE)
print("Gradient accumulation:", GRADIENT_ACCUMULATION_STEPS)
print("Optimization steps:", total_steps)
print("Device:", device)
print("=" * 60)

# ------------------------------------------------------------
# Training loop
# ------------------------------------------------------------

for batch_idx, batch in enumerate(train_dataloader):

    # Move batch to MPS
    batch = {
        key: value.to(device)
        for key, value in batch.items()
    }

    # Forward pass
    outputs = model(**batch)

    loss = outputs.loss

    # Scale loss for gradient accumulation
    scaled_loss = loss / GRADIENT_ACCUMULATION_STEPS

    # Backward pass
    scaled_loss.backward()

    running_loss += loss.item()
    epoch_loss += loss.item()

    # Optimizer update
    if (
        (batch_idx + 1) % GRADIENT_ACCUMULATION_STEPS == 0
        or (batch_idx + 1) == total_batches
    ):

        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=1.0
        )

        optimizer.step()
        optimizer.zero_grad()

        current_step = (
            (batch_idx + 1) // GRADIENT_ACCUMULATION_STEPS
        )

        # Print progress every 100 optimization steps
        if current_step % 100 == 0 or current_step == total_steps:

            avg_loss = running_loss / (
                100 * GRADIENT_ACCUMULATION_STEPS
            )

            elapsed = time.time() - start_time

            print(
                f"Step {current_step:4d}/{total_steps} | "
                f"Avg loss: {avg_loss:.4f} | "
                f"Time: {elapsed/60:.1f} min"
            )

            running_loss = 0.0

# ------------------------------------------------------------
# Training summary
# ------------------------------------------------------------

average_training_loss = epoch_loss / total_batches

elapsed_total = time.time() - start_time

print("\n" + "=" * 60)
print("TRAINING COMPLETED")
print("=" * 60)

print("Average training loss:", round(average_training_loss, 4))
print("Total training time:", round(elapsed_total / 60, 2), "minutes")
print("Optimization steps:", total_steps)

Starting T5-small training...
============================================================
Training examples: 20000
Epochs: 1
Batch size: 2
Gradient accumulation: 4
Optimization steps: 2500
Device: mps
============================================================
Step  100/2500 | Avg loss: 2.1967 | Time: 3.1 min
Step  200/2500 | Avg loss: 2.1496 | Time: 6.1 min
Step  300/2500 | Avg loss: 2.0808 | Time: 9.1 min
Step  400/2500 | Avg loss: 2.1283 | Time: 12.1 min
Step  500/2500 | Avg loss: 2.0996 | Time: 15.1 min
Step  600/2500 | Avg loss: 2.0605 | Time: 18.1 min
Step  700/2500 | Avg loss: 2.0558 | Time: 21.2 min
Step  800/2500 | Avg loss: 2.0778 | Time: 24.3 min
Step  900/2500 | Avg loss: 2.0780 | Time: 27.2 min
Step 1000/2500 | Avg loss: 2.0389 | Time: 30.2 min
Step 1100/2500 | Avg loss: 2.0278 | Time: 33.2 min
Step 1200/2500 | Avg loss: 2.0074 | Time: 36.2 min
Step 1300/2500 | Avg loss: 2.0387 | Time: 39.1 min
Step 1400/2500 | Avg loss: 2.1027 | Time: 42.1 min
Step 1500/2500 | Avg loss: 2.0894 | Time: 45.1 min
Step 1600/2500 | Avg loss: 2.0879 | Time: 48.1 min
Step 1700/2500 | Avg loss: 2.0115 | Time: 51.1 min
Step 1800/2500 | Avg loss: 2.0512 | Time: 54.0 min
Step 1900/2500 | Avg loss: 2.0486 | Time: 57.5 min
Step 2000/2500 | Avg loss: 2.0449 | Time: 60.5 min
Step 2100/2500 | Avg loss: 2.0413 | Time: 63.6 min
Step 2200/2500 | Avg loss: 2.0279 | Time: 66.6 min
Step 2300/2500 | Avg loss: 2.0352 | Time: 69.7 min
Step 2400/2500 | Avg loss: 2.0324 | Time: 72.8 min
Step 2500/2500 | Avg loss: 2.0484 | Time: 76.1 min

============================================================
TRAINING COMPLETED
============================================================
Average training loss: 2.0664
Total training time: 76.08 minutes
Optimization steps: 2500

In [183]:
# ============================================================
# STEP 60.14: CALCULATE VALIDATION LOSS
# ============================================================

import torch
import time

model.eval()

validation_loss = 0.0
validation_batches = 0

start_time = time.time()

print("Evaluating validation dataset...")
print("=" * 60)

with torch.no_grad():

    for batch in validation_dataloader:

        # Move batch to MPS
        batch = {
            key: value.to(device)
            for key, value in batch.items()
        }

        # Forward pass
        outputs = model(**batch)

        validation_loss += outputs.loss.item()
        validation_batches += 1

validation_loss = validation_loss / validation_batches

elapsed = time.time() - start_time

print("\nValidation completed.")
print("=" * 60)
print("Validation batches:", validation_batches)
print("Average validation loss:", round(validation_loss, 4))
print("Evaluation time:", round(elapsed / 60, 2), "minutes")

Evaluating validation dataset...
============================================================

Validation completed.
============================================================
Validation batches: 1000
Average validation loss: 1.79
Evaluation time: 1.81 minutes

In [188]:
# ============================================================
# STEP 60.15: TEST THE TRAINED SUMMARIZATION MODEL
# ============================================================

import torch
import time

model.eval()

print("=" * 70)
print("SAMPLE SUMMARIZATION TEST")
print("=" * 70)

# Use the original CNN/DailyMail test split
test_dataset = dataset["test"]

# Select three examples
sample_indices = [0, 1, 2]

for i, idx in enumerate(sample_indices, start=1):

    # Get original article and reference summary
    article = test_dataset[idx]["article"]
    reference = test_dataset[idx]["highlights"]

    # Prepare input
    input_text = "summarize: " + article

    inputs = tokenizer(
        input_text,
        max_length=512,
        truncation=True,
        return_tensors="pt"
    )

    # Move inputs to MPS
    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Generate summary
    start_time = time.time()

    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_length=128,
            num_beams=4,
            length_penalty=1.0,
            early_stopping=True
        )

    generation_time = time.time() - start_time

    # Decode generated summary
    generated_summary = tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    )

    print(f"\n{'=' * 70}")
    print(f"SAMPLE {i}")
    print(f"{'=' * 70}")

    print("\nREFERENCE SUMMARY:")
    print(reference)

    print("\nGENERATED SUMMARY:")
    print(generated_summary)

    print("\nGeneration time:", round(generation_time, 2), "seconds")

======================================================================
SAMPLE SUMMARIZATION TEST
======================================================================

======================================================================
SAMPLE 1
======================================================================

REFERENCE SUMMARY:
Membership gives the ICC jurisdiction over alleged crimes committed in Palestinian territories since last June .
Israel and the United States opposed the move, which could open the door to war crimes investigations against Israelis .

GENERATED SUMMARY:
The Palestinian Authority officially becomes the 123rd member of the International Criminal Court. The formal accession was marked with a ceremony at The Hague, in the Netherlands. The Palestinians signed the ICC's founding Rome Statute in January.

Generation time: 3.98 seconds

======================================================================
SAMPLE 2
======================================================================

REFERENCE SUMMARY:
Theia, a bully breed mix, was apparently hit by a car, whacked with a hammer and buried in a field .
"She's a true miracle dog and she deserves a good life," says Sara Mellado, who is looking for a home for Theia .

GENERATED SUMMARY:
Theia is a friendly white-and-black bully breed mix now named Theia. She was found by a worker who took her to a vet for help. Theia suffered a dislocated jaw, leg injuries and a caved-in sinus cavity.

Generation time: 0.92 seconds

======================================================================
SAMPLE 3
======================================================================

REFERENCE SUMMARY:
Mohammad Javad Zarif has spent more time with John Kerry than any other foreign minister .
He once participated in a takeover of the Iranian Consulate in San Francisco .
The Iranian foreign minister tweets in English .

GENERATED SUMMARY:
Mohammad Javad Zarif has been U.S. Secretary of State John Kerry's opposite number in securing breakthrough in nuclear talks. Zarif tweeted "Happy Rosh Hashanah," referring to Jewish New Year.

Generation time: 0.98 seconds

In [187]:
# ============================================================
# STEP 60.15A: FIND THE EXISTING DATASET VARIABLE
# ============================================================

print("Checking available dataset variables...\n")

dataset_variables = [
    "dataset",
    "cnn_dailymail",
    "raw_datasets",
    "train_dataset",
    "validation_dataset",
    "test_dataset",
    "tokenized_datasets",
    "tokenized_train",
    "tokenized_validation",
    "tokenized_test"
]

for name in dataset_variables:
    if name in globals():
        print("✓", name, "exists")
        print("  Type:", type(globals()[name]))
    else:
        print("✗", name, "not found")

Checking available dataset variables...

✓ dataset exists
  Type: <class 'datasets.dataset_dict.DatasetDict'>
✗ cnn_dailymail not found
✗ raw_datasets not found
✗ train_dataset not found
✗ validation_dataset not found
✗ test_dataset not found
✗ tokenized_datasets not found
✓ tokenized_train exists
  Type: <class 'datasets.arrow_dataset.Dataset'>
✓ tokenized_validation exists
  Type: <class 'datasets.arrow_dataset.Dataset'>
✓ tokenized_test exists
  Type: <class 'datasets.arrow_dataset.Dataset'>

In [189]:
# ============================================================
# STEP 60.16: ROUGE EVALUATION
# ============================================================

import torch
import time
import numpy as np
from evaluate import load

model.eval()

# Load ROUGE metric
rouge = load("rouge")

# Use the 2,000-example test subset created earlier
evaluation_dataset = dataset["test"].shuffle(seed=42).select(range(2000))

predictions = []
references = []

print("=" * 70)
print("ROUGE EVALUATION")
print("=" * 70)
print("Test examples:", len(evaluation_dataset))
print("This may take some time on MPS...")
print()

start_time = time.time()

for i, example in enumerate(evaluation_dataset):

    article = example["article"]
    reference = example["highlights"]

    # Prepare input
    inputs = tokenizer(
        "summarize: " + article,
        max_length=512,
        truncation=True,
        return_tensors="pt"
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Generate summary
    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_length=128,
            num_beams=4,
            length_penalty=1.0,
            early_stopping=True
        )

    # Decode
    prediction = tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    )

    predictions.append(prediction)
    references.append(reference)

    # Progress
    if (i + 1) % 100 == 0:
        elapsed = time.time() - start_time
        print(
            f"Processed {i + 1}/2000 "
            f"| Time: {elapsed / 60:.1f} min"
        )

# Calculate ROUGE
results = rouge.compute(
    predictions=predictions,
    references=references,
    use_stemmer=True
)

elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("ROUGE EVALUATION COMPLETED")
print("=" * 70)

print("ROUGE-1:", round(results["rouge1"], 4))
print("ROUGE-2:", round(results["rouge2"], 4))
print("ROUGE-L:", round(results["rougeL"], 4))
print("ROUGE-Lsum:", round(results["rougeLsum"], 4))

print("\nEvaluation time:", round(elapsed / 60, 2), "minutes")

Downloading builder script: 6.14kB [00:00, 1.79MB/s]

======================================================================
ROUGE EVALUATION
======================================================================
Test examples: 2000
This may take some time on MPS...

Processed 100/2000 | Time: 2.1 min
Processed 200/2000 | Time: 4.2 min
Processed 300/2000 | Time: 6.4 min
Processed 400/2000 | Time: 8.6 min
Processed 500/2000 | Time: 10.8 min
Processed 600/2000 | Time: 12.9 min
Processed 700/2000 | Time: 14.9 min
Processed 800/2000 | Time: 17.0 min
Processed 900/2000 | Time: 19.2 min
Processed 1000/2000 | Time: 21.3 min
Processed 1100/2000 | Time: 23.3 min
Processed 1200/2000 | Time: 25.4 min
Processed 1300/2000 | Time: 27.6 min
Processed 1400/2000 | Time: 37.4 min
Processed 1500/2000 | Time: 39.5 min
Processed 1600/2000 | Time: 41.5 min
Processed 1700/2000 | Time: 43.8 min
Processed 1800/2000 | Time: 45.9 min
Processed 1900/2000 | Time: 48.0 min
Processed 2000/2000 | Time: 50.7 min

======================================================================
ROUGE EVALUATION COMPLETED
======================================================================
ROUGE-1: 0.4132
ROUGE-2: 0.1919
ROUGE-L: 0.2905
ROUGE-Lsum: 0.3559

Evaluation time: 50.79 minutes

In [190]:
# ============================================================
# STEP 60.17: SAVE TRAINED T5 SUMMARIZATION MODEL
# ============================================================

import os
import json
import torch

# Create directory
summarizer_dir = "t5_summarizer"

os.makedirs(summarizer_dir, exist_ok=True)

print("=" * 70)
print("SAVING TRAINED T5 SUMMARIZATION MODEL")
print("=" * 70)

# Save model
model.save_pretrained(summarizer_dir)

# Save tokenizer
tokenizer.save_pretrained(summarizer_dir)

# Save project metadata
metadata = {
    "model_checkpoint": "google-t5/t5-small",
    "dataset": "CNN/DailyMail",
    "training_examples": 20000,
    "validation_examples": 2000,
    "evaluation_examples": 2000,
    "epochs": 1,
    "learning_rate": 5e-5,
    "batch_size": 2,
    "gradient_accumulation_steps": 4,
    "max_input_length": 512,
    "max_target_length": 128,
    "training_loss": 2.0664,
    "validation_loss": 1.7900,
    "rouge1": 0.4132,
    "rouge2": 0.1919,
    "rougeL": 0.2905,
    "rougeLsum": 0.3559
}

with open(
    os.path.join(summarizer_dir, "training_metadata.json"),
    "w"
) as f:
    json.dump(metadata, f, indent=4)

print("\nModel saved to:", os.path.abspath(summarizer_dir))

print("\nSaved files:")

for file in sorted(os.listdir(summarizer_dir)):
    print("  ✓", file)

print("\n" + "=" * 70)
print("SUMMARIZATION MODEL SAVED SUCCESSFULLY")
print("=" * 70)

======================================================================
SAVING TRAINED T5 SUMMARIZATION MODEL
======================================================================

Writing model shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.20it/s]

Model saved to: /Users/hemanthreddy/Downloads/t5_summarizer

Saved files:
  ✓ config.json
  ✓ generation_config.json
  ✓ model.safetensors
  ✓ tokenizer.json
  ✓ tokenizer_config.json
  ✓ training_metadata.json

======================================================================
SUMMARIZATION MODEL SAVED SUCCESSFULLY
======================================================================